### ISSUE TITLE
version is too dynamic

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/taskcat#129]
**Describe the bug**
https://github.com/aws-quickstart/taskcat/blob/develop/setup.py#L5-L7

Looks to me like anyone running this script will end up with a version number that depicts install time, not build/release time.

**To Reproduce**

`python setup.py install > /dev/null ; taskcat --version ; sleep 61 ; python setup.py install > /dev/null ; taskcat --version`

**Expected behavior**

version numbers should reflect build or commit time, not install time

**Comment by avattathil** [comment]
What if we mod setup.py to only do a version bump when _build_ is passed in as an argument to setup.py then edit this [line](https://github.com/aws-quickstart/taskcat/blob/develop/.travis.yml#L9) to `python setup.py build && python setup.py install` 

Anyone have a better way to handle this?
