### ISSUE TITLE
ci/taskcat_project_override.json not honored

### ISSUE THREAD

**Issue by sshvans** [aws-quickstart/taskcat#167]
**Describe the bug**
taskcat_project_override.json file is not honored even if it exist in the ci/ folder.

**To Reproduce**
1. Take any Quick Start
2. Create ci/taskcat_project_override.json file and add some parameter values for those parameters which are specified in inputs file.
3. Run taskcat.

**Expected behavior**
I expect the parameter value defined in inputs file overriden by the parameter value in the taskcat_project_override.json file.

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version - version 0.7.27

**Comment by agamzn** [comment]
This is stop-gap fixed in https://github.com/aws-quickstart/taskcat/commit/6b985d46df59e2fd9095a159525955c00509b070

Longer-term we need to address how to better handle ci/taskcat_project_override.json, as it's currently fetched from S3.

**Comment by agamzn** [comment]
Circling back: long term we need to look at the config the filesystem level. This is blocked pending #174 , as we need to know where the config file is.
