### ISSUE TITLE
Deep cleanup fails on Jenkins

### ISSUE THREAD

**Issue by vsnyc** [aws-quickstart/taskcat#168]
Bug in deep cleanup

Traceback:
20:21:23 [0;30;43m[INFO   ][0m :Few stacks failed to delete. Collecting resources for deep clean-up.
20:21:23 Traceback (most recent call last):
20:21:23   File "/var/lib/jenkins/.local/bin/taskcat", line 88, in <module>
20:21:23     main()
20:21:23   File "/var/lib/jenkins/.local/bin/taskcat", line 81, in main
20:21:23     tcat_instance.cleanup(testdata, 5)
20:21:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/taskcat/stacker.py", line 1320, in cleanup
20:21:23     self.deep_cleanup(testdata_list)
20:21:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/taskcat/stacker.py", line 1347, in deep_cleanup
20:21:23     failed_stacks = self.get_all_resources(failed_stack_ids, region)
20:21:23 AttributeError: 'TaskCat' object has no attribute 'get_all_resources'

**Comment by vsnyc** [comment]
After the above fix, a new issue popped up. Looking at the code, it seems like the `region` was not present in stackdata?

            stackdata = CommonTools(failed_stack_ids[0]).parse_stack_info()
            region = stackdata['region']

Traceback:
```
15:25:36 [0;30;43m[INFO   ][0m :Few stacks failed to delete. Collecting resources for deep clean-up.
15:25:36 Traceback (most recent call last):
15:25:36   File "/var/lib/jenkins/.local/bin/taskcat", line 88, in <module>
15:25:36     main()
15:25:36   File "/var/lib/jenkins/.local/bin/taskcat", line 81, in main
15:25:36     tcat_instance.cleanup(testdata, 5)
15:25:36   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/taskcat/stacker.py", line 1321, in cleanup
15:25:36     self.deep_cleanup(testdata_list)
15:25:36   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/taskcat/stacker.py", line 1349, in deep_cleanup
15:25:36     failed_stacks = CfnResourceTools.get_all_resources(failed_stack_ids, region)
15:25:36 TypeError: get_all_resources() missing 1 required positional argument: 'region'
15:25:36 Build step 'Execute shell' marked build as failure
15:25:36 Checking console output
```

**Comment by agamzn** [comment]
I'm hitting this as well.

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/taskcat/commit/d59d8f915f1e881cbae901a0560fa320540380fa
