### ISSUE TITLE
Need more flexibility around root directory name

### ISSUE THREAD

**Issue by agamzn** [aws-quickstart/taskcat#174]
**Describe the bug**
Currently taskcat mandates the root directory of the project matches the value of the `qsname` key in the config. Depending on organizational rules, this may not be practical. 

From my perspective, this can be fixed in a forward and backwards-compatible approach by.. 
- Inferring the root directory by assuming the project structure is <`rootdir>/ci/(config_file.name)`
- Adding the -`-project-root-dir flag` to allow end-users to specify a custom path to the config file, and a custom path to a project. This is a value add for end-users that have custom directory structures as mandated by organizational policies.

**Comment by avattathil** [comment]
As part of this change we should change `global:qsname` to `global:project` (while allowing qsname to still be valid)
