### ISSUE TITLE
Adding testcase scenario examples in documentation

### ISSUE THREAD

**Issue by viralmutant** [aws-quickstart/taskcat#20]
This is more of a request than an issue.

From the documentation I could not figure out how to write sample testcases for my CFN template in config.yml
And what exactly can I test with this utility ?

Can you please point me to some examples ?

**Comment by sshvans** [comment]
Thanks for reaching out!
Taskcat is a command line tool to test your CFN templates in multiple regions in parallel, with different inputs.
You define the test cases in the config.yml file by providing different input parameter files and regions, against which you want to test your CloudFormation template.

[Here](https://github.com/aws-quickstart/taskcat/blob/master/examples/sample-taskcat-project/ci/taskcat.yml) is the link to a sample config file.
In this file, there is one testcase defined named "taskcat-test1", which tests the CFN template named "debug.template" in "us-east-1" region with the parameter values provided in "debug-input.json" file. You can list multiple regions in one test.

I hope it helps you understand how you can use TaskCat. Let me know if this answers your question and I'll close this issue.

**Comment by viralmutant** [comment]
I was thinking that since there are various methods defined in taskcat class, I will be able to create testcases based upon those methods. That is not the case ?

The tastcat_test.py, which eventually is 'taskcat' binary, at present will just create a stack for each test scenario

If I wish to do further operations after stack creation, in each test case, how should I do that ?

**Comment by sshvans** [comment]
What type of testcases are you thinking of?
Currently, taskcat creates a stack for each test case defined in config.yml file, deletes the stack once stack is finished and generates a report.
Knowing what type of testcases do you have in mind, I'll be able to better assist you.

**Comment by viralmutant** [comment]
I was thinking if I could run some test scripts after stack creation.
The test scripts may either do some security checks, penetration testing etc.
Also if we are using auto scaling feature, if I can test that as well by simulating load etc.

**Comment by avattathil** [comment]
@viralmutant Thanks for the feedback we will consider the above request as feature adds. 
Enhancement added to backlog

**Comment by avattathil** [comment]
Backlog id ` [P8437964] ` (Internal use only)
