### ISSUE TITLE
Need to parse an empty parameter_input file

### ISSUE THREAD

**Issue by ustrahlendorf** [aws-quickstart/taskcat#201]
My cf-template already has the parameters section filled with the needed values.
Need to know the structure to parse an empty parameter_input file or a feature to tell taskcat that no parameter_input file is needed.

**Comment by avattathil** [comment]
You should be able to pass an input file that has no key values defined.
create the file like this `echo "[{}]" >yourrepo/ci/input.json`

in the `ci/taskcat.yml` to reference the input.json as the input file  
example [here](https://github.com/aws-quickstart/taskcat/blob/master/examples/sample-taskcat-project/ci/taskcat-autobucket.yml#L19)

I have not tested this but it should work. Let us know if it solves your use-case

**Comment by ustrahlendorf** [comment]
I tested it, unfortunately no luck.
Here my input.json
[{}]
Here the output of taskcat:
[test-project1.log](https://github.com/aws-quickstart/taskcat/files/2591274/test-project1.log)

**Comment by jaymccon** [comment]
Can confirm Im getting the same symptoms with `[{}]` as params file. Investigating cause...

**Comment by jaymccon** [comment]
@ustrahlendorf you can use `[]` successfully. I think that behavior is fine, as a 0 length list works as expected, and if an element is present in the list (`[{}]`) it is expected to contain a `ParameterKey` key. 

Error message could be better though.

**Comment by ustrahlendorf** [comment]
Can confirm that using [] in the parameter_input file works.
Thanks for the help.
Might be an idea to make it a bit easier for example don't require a parameter_input value, make it optional

**Comment by jofwar** [comment]
Hi folks,

I'm trying to use an empty parameter file with just [] but i'm getting a Traceback.

```
[INFO   ] :|Processing Overrides
Traceback (most recent call last):
  File "/Users/---/.pyenv/versions/3.6.0/bin/taskcat", line 101, in <module>
    main()
  File "/Users/---/.pyenv/versions/3.6.0/bin/taskcat", line 88, in main
    testdata = tcat_instance.stackcreate(taskcat_cfg, test_list, args.stack_prefix)
  File "/Users/---/.pyenv/versions/3.6.0/lib/python3.6/site-packages/taskcat/stacker.py", line 706, in stackcreate
    s_include_params = self.get_param_includes(s_parms)
  File "/Users/---/.pyenv/versions/3.6.0/lib/python3.6/site-packages/taskcat/stacker.py", line 323, in get_param_includes
    template_params = self.extract_template_parameters()
  File "/Users/---/.pyenv/versions/3.6.0/lib/python3.6/site-packages/taskcat/stacker.py", line 561, in extract_template_parameters
    return self.template_data['Parameters'].keys()
KeyError: 'Parameters'
```

**Comment by agamzn** [comment]
Interesting, is the template something you can share? It's throwing a traceback while looking for the 'Parameters' section of your template.  What taskcat version is this? Do you see this if you provide a parameter (default value is fine).

**Comment by jofwar** [comment]
unfortunately i can't share the template due to secrets laced throughout but it essentially just creates roles and policies.. The template itself deploys correctly since it's already in production.  
I first used the latest docker image which i believe is version 2018.817.210357. This actually doesn't throw a traceback, instead gives
```
[INFO   ] :Preparing to launch in region [eu-west-1] 
[INFO   ] :|Processing Overrides
[ERROR  ] :'Parameters'
[FAIL   ] :Cannot launch stackSet.yml
```

traceback happens with version 0.8.23.

if the template is required i will trim and remove any sensitive data and post it.

**Comment by agamzn** [comment]
@jofwar  - Thanks for the confirmation - no need to post the template, the traceback gives a bit of a red herring. This is on our radar.

**Comment by sshvans** [comment]
Fixed in [release 0.8.27](https://github.com/aws-quickstart/taskcat/releases/tag/0.8.27)

**Comment by zaro0508** [comment]
Is this really fixed?  I'm using taskcat ver 0.8.30 and I can't seem to get a template without any parameter to run.  The template is here: https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/dlm-role.yaml

I tried with following scenarios:
```
A. empty json (i.e. [{}])
Result: [ERROR  ] :Invalid parameter {} all items must have both ParameterKey and ParameterValue keys

B. remove "parameter_input" from input.json file
Result: No key parameter_input in testdlm-role [ERROR  ] :While inspecting: regions

C. dummy value (i.e. [{"ParameterKey": "dummy", "ParameterValue": "value"}])
Result:
[DEBUG  ] :Parameters:
[DEBUG  ] :Tags:[{'Key': 'owner', 'Value': 'taskcat'}]
Traceback (most recent call last):
  File "/Users/zaro0508/.virtualenvs/py36-taskcat/bin/taskcat", line 101, in <module>
    main()
  File "/Users/zaro0508/.virtualenvs/py36-taskcat/bin/taskcat", line 88, in main
    testdata = tcat_instance.stackcreate(taskcat_cfg, test_list, args.stack_prefix)
  File "/Users/zaro0508/.virtualenvs/py36-taskcat/lib/python3.6/site-packages/taskcat/stacker.py", line 743, in stackcreate
    Tags=self.tags
  File "/Users/zaro0508/.virtualenvs/py36-taskcat/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-taskcat/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: Parameter values specified for a template which does not require them.
```

My Environment:
```
❯❯❯ https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/dlm-role.yaml

❯❯❯ python -V                                                                                                                                                     Python 3.6.3

❯❯❯ taskcat --version                                                                                                                                           0.8.30

❯❯❯ pip freeze                                                                                                                                                 
aws-sam-translator==1.10.0
awscli==1.16.122
boto3==1.9.112
botocore==1.12.112
certifi==2019.3.9
cfn-lint==0.15.0
chardet==3.0.4
colorama==0.3.9
docutils==0.14
idna==2.8
Jinja2==2.10
jmespath==0.9.4
jsonpatch==1.23
jsonpointer==2.0
jsonschema==2.6.0
MarkupSafe==1.1.1
mock==2.0.0
pbr==5.1.3
pyasn1==0.4.5
pyfiglet==0.8.post1
python-dateutil==2.8.0
PyYAML==3.13
requests==2.21.0
rsa==3.4.2
s3transfer==0.2.0
six==1.12.0
tabulate==0.8.3
taskcat==0.8.30
urllib3==1.24.1
yattag==1.11.1
```

**Comment by andrew-glenn** [comment]
reopening.

**Comment by andrew-glenn** [comment]
Decided it's best to tackle in v0.9 as we're doing a bunch of restructuring anyway.

**Comment by jaymccon** [comment]
latest release removes the need for a parameters file altogether. parameters (if needed) can be defined in the project config file. Here's an example with no parameters: https://github.com/aws-quickstart/taskcat/blob/master/tests/data/lint-error/.taskcat.yml and one with a parameter defined https://github.com/aws-quickstart/taskcat/blob/master/tests/data/lambda_build_with_submodules/.taskcat.yml
