### ISSUE TITLE
Need explanation what "reporting:" is doing

### ISSUE THREAD

**Issue by ustrahlendorf** [aws-quickstart/taskcat#202]
in the example config file "taskcat.yml" (see below) there is a line with "reporting: true". What exactly is the purpose, what values are valid (true, false, ???)
I could not see any difference when using the line or not.

---
global:
  owner: owner@company.com
  qsname: sample-taskcat-project
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
tests:
  taskcat-json:
    parameter_input: debug-input.json
    regions:
      - us-east-1
    template_file: debug.template

**Comment by avattathil** [comment]
That key actually is not needed. I will remove it for the sample config. It is a legacy key that got left in the examples. Thanks for reporting this.

**Comment by ustrahlendorf** [comment]
ok, I deleted "reporting: true" unfortunately it stops and asked for the reporting line.
Here my config
---
global:
  owner: ustrahlendorf@tecracer.de
  qsname: test-project1
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
tests:
  scenario-1:
    parameter_input: input.json
    regions:
      - eu-central-1
    template_file: NetworkLayer.yml

Output is attached
[test-project1_noReporting.log](https://github.com/aws-quickstart/taskcat/files/2591284/test-project1_noReporting.log)

**Comment by avattathil** [comment]
Will remove check for the `reporting` key in the next release
