### ISSUE TITLE
Mismatch between StackID and StackName in CFNResourceTools

### ISSUE THREAD

**Issue by agamzn** [aws-quickstart/taskcat#207]
# The bug

There's a mismatch between StackID and StackName in the `CFNResourceTools.get_all_resources` code path. 

Here's where it's invoked. 

https://github.com/aws-quickstart/taskcat/blob/0c38763b57e95a60f3aa84a3d8e4ad80d7d86be8/taskcat/stacker.py#L1350

The get_all_resources function does a bunch of housekeeping, then calls out to `CFNResourceTools.get_resources`, passing a StackID.

https://github.com/aws-quickstart/taskcat/blob/0c38763b57e95a60f3aa84a3d8e4ad80d7d86be8/taskcat/cfn_resources.py#L104-L109

Based on the `CFNResourceTools.get_resources` parameters, it expects a StackName

https://github.com/aws-quickstart/taskcat/blob/0c38763b57e95a60f3aa84a3d8e4ad80d7d86be8/taskcat/cfn_resources.py#L11

It passed that variable on to the helper...

https://github.com/aws-quickstart/taskcat/blob/0c38763b57e95a60f3aa84a3d8e4ad80d7d86be8/taskcat/cfn_resources.py#L31-L34

.. that makes an API call, expecting to pass in a StackName (i[n compliant with the boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.describe_stack_resources).

https://github.com/aws-quickstart/taskcat/blob/0c38763b57e95a60f3aa84a3d8e4ad80d7d86be8/taskcat/cfn_resources.py#L42

# The behavior within taskcat.

Sometimes this fails, causing Taskcat to raise, and the test to exit 1.

`09:34:19 [ERROR  ] :An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with id arn:aws:cloudformation:eu-west-1:[redacted]:stack/[redacted] does not exist`

**Comment by avattathil** [comment]
Potential fix: Use [CommonTools(stack_id).parse_stack_info()](https://github.com/aws-quickstart/taskcat/blob/master/taskcat/common_utils.py#L31) to parse the stackid which will return a list the info['stackname']

**Comment by agamzn** [comment]
Looking further: StackID and StackName are interchangable in certain conditions (where this is triggered). Investigating an upstream bug.

**Comment by agamzn** [comment]
er... looks like I hit a red herring; digging further; closing for now
