### ISSUE TITLE
TaskCat always returns exit code 0

### ISSUE THREAD

**Issue by setswei** [aws-quickstart/taskcat#223]
When i use taskcat to test a template i have been working on. i found a issue if a cloudformation template reports create_failed Taskcat reports that as Informational (as per the code snip below) shouldn't this be shown as a error and fail the test or does something else need to be configured in the taskcat.yaml file that i am missing ?

`
[INFO   ] :AWS REGION      CLOUDFORMATION STACK STATUS [CLOUDFORMATION STACK NAME]
[INFO   ] :ap-southeast-2  CREATE_FAILED                                   [tCaT-tag-Template1-deac1cd6]
[INFO   ] :ap-southeast-2  CREATE_COMPLETE                            [tCaT-tag-Template2-deac1cd6]
[INFO   ] :ap-southeast-2  CREATE_COMPLETE                            [tCaT-tag-Template3-deac1cd6]
`

1. using a custom template
2. Install with pip3
3. Using a profile
4. Is your AWS environment configured via `aws configure` -- Yes
5. On first run of the template everything is ok i have only run into a issue were the cloudformation template has the Retain option configured on a IAM role or s3 bucket and the template tries to create the resource with the same name and fails

**Expected behavior**
If a Create_Failed occurs i would expect to see that show as a error in the taskcat report so build processes will see that as a failure

 - Taskcat Version 0.8.19

**Comment by agamzn** [comment]
@setswei I've been able to reproduce this. The CREATE_FAILED as an informational logging is cosmetic and we're happy to change that. However, the zero exit code is a problem. digging further.
```
[INFO   ] :AWS REGION      CLOUDFORMATION STACK STATUS [CLOUDFORMATION STACK NAME]
[INFO   ] :us-east-2       CREATE_IN_PROGRESS        [tCaT-tag-xxyy]


[INFO   ] :AWS REGION      CLOUDFORMATION STACK STATUS [CLOUDFORMATION STACK NAME]
[INFO   ] :us-east-2       CREATE_IN_PROGRESS        [tCaT-tag-xxyy]


[INFO   ] :AWS REGION      CLOUDFORMATION STACK STATUS [CLOUDFORMATION STACK NAME]
[INFO   ] :us-east-2       CREATE_FAILED             [tCaT-tag-xxyy]


[taskcat] |GENERATING REPORTS
[INFO   ] :Creating report in [taskcat_outputs]
[INFO   ] :Collecting CloudFormation Logs
[INFO   ] :Collecting logs for tCaT-tag-xxyy"

         |StackName: tCaT-tag-xxyy
         |Region: us-east-2
         |Logging to: taskcat_outputs/tCaT-tag-xxyy-us-east-2-cfnlogs.txt
         |Tested on: Thursday, 27. December 2018 10:10AM
------------------------------------------------------------------------------------------
ResourceStatusReason:
The following resource(s) failed to create: [VPCStack].
==========================================================================================
[INFO   ] :Resources: for tCaT-xxyy
[INFO   ] :
                LogicalId = VPCStack,
                PhysicalId = None,
                Type = AWS::CloudFormation::Stack
[INFO   ] :(Generating Reports)
[INFO   ] : - Processing XXXYYY
Reporting on arn:aws:cloudformation:us-east-2:XXXXXXX:stack/tCaT-tag-xxyy


[DEBUG  ] :clean-up = True
[taskcat] |CLEANUP STACKS


[INFO   ] :AWS REGION      CLOUDFORMATION STACK STATUS [CLOUDFORMATION STACK NAME]
[INFO   ] :us-east-2       DELETE_IN_PROGRESS        [tCaT-tag-xxyy]


[INFO   ] :AWS REGION      CLOUDFORMATION STACK STATUS [CLOUDFORMATION STACK NAME]
[INFO   ] :us-east-2       STACK_DELETED             [tCaT-tag-xxyy]


[INFO   ] :All stacks deleted successfully. Deep clean-up not required.
[INFO   ] :(Cleaning up staging assets)
[INFO   ] :Deleted 27 objects from taskcat-tag-xxyy
[DEBUG  ] :Deleting Bucket taskcat-tag-xxyy

development/quickstarts/mine took 36s
➜ echo $?
0
```

**Comment by agamzn** [comment]
@setswei  - Are you using taskcat as a module or as the standalone utility? Either way, we need to fix this, but we're always curious how this is being used. Feedback is appreciated.

**Comment by setswei** [comment]
Hey @agamzn  

Sorry for the delay in response been away for holidays etc

currently i am looking at using task cat in my build pipelines (so it would be used in a build process as a standalone application that is called by a pipeline to conduct tests) as the end goal for me was to use taskcat as a way of validating that changes or new cloudformation templates that would then deployed deployed to a s3 bucket we use as a central repo for templates as we managed multiple aws accounts

we would like to use this process of a way of controlling particular changes in production environments etc with out giving developers access to the s3 bucket were the templates are stored

is there any more info that i can provide ?

**Comment by agamzn** [comment]
@setswei  - That helps us a ton, thank you!

**Comment by agamzn** [comment]
Merged PR: https://github.com/aws-quickstart/taskcat/pull/234

This is just pending the next release cut. Expect that in the next day or so
