### ISSUE TITLE
Running multiple tests with the same parameter_input file

### ISSUE THREAD

**Issue by tbulding** [aws-quickstart/taskcat#225]
When needing to run a series of tests on templates that all use the same set of parameters, it would be nice to just use a single parameter_input file plus additional parameters for those elements that the templates do not have in common.

Example:
Test 1:
  {
    "ParameterKey": "AMIOS",
    "ParameterValue": "CentOS-7-HVM"
  },
  {
    "ParameterKey": "fname",
    "ParameterValue": "john"
  },
  {
    "ParameterKey": "lname",
    "ParameterValue": "doe"
  },

Test 2:
  {
    "ParameterKey": "AMIOS",
    "ParameterValue": "Ubuntu"
  },
  {
    "ParameterKey": "fname",
    "ParameterValue": "john"
  },
  {
    "ParameterKey": "lname",
    "ParameterValue": "doe"
  },

Test3:
  {
    "ParameterKey": "AMIOS",
    "ParameterValue": "Windows"
  },
  {
    "ParameterKey": "fname",
    "ParameterValue": "john"
  },
  {
    "ParameterKey": "lname",
    "ParameterValue": "doe"
  },

In the examples above, the parameters are all the same except for the AMIOS, Ideally, they would pull the parameters in common from the same parameter_input file

**Comment by agamzn** [comment]
@tbulding  - would per-test overrides in #122 solve this?

**Comment by jaymccon** [comment]
overrides can now be done globally in `~/.taskcat.yml`, per project in the `project` section, or per test in the `tests` test definition.
