### ISSUE TITLE
CREATE_FAILED is shown as Informational

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/taskcat#233]
This was originally reported by @setswei in #223. Migrating that here for further tracking. 

https://github.com/aws-quickstart/taskcat/issues/223#issue-392130232

> When i use taskcat to test a template i have been working on. i found a issue if a cloudformation template reports create_failed Taskcat reports that as Informational (as per the code snip below) shouldn't this be shown as a error and fail the test or does something else need to be configured in the taskcat.yaml file that i am missing ?
> 
> `[INFO ] :AWS REGION CLOUDFORMATION STACK STATUS [CLOUDFORMATION STACK NAME] [INFO ] :ap-southeast-2 CREATE_FAILED [tCaT-tag-Template1-deac1cd6] [INFO ] :ap-southeast-2 CREATE_COMPLETE [tCaT-tag-Template2-deac1cd6] [INFO ] :ap-southeast-2 CREATE_COMPLETE [tCaT-tag-Template3-deac1cd6]`
> 
> Steps to reproduce the behavior:
> 
> 1. using a custom template
> 2. Install with pip3
> 3. Using a profile
> 4. Is your AWS environment configured via `aws configure` -- Yes
> 5. On first run of the template everything is ok i have only run into a issue were the cloudformation template has the Retain option configured on a IAM role or s3 bucket and the template tries to create the resource with the same name and fails
> 
> **Expected behavior**
> If a Create_Failed occurs i would expect to see that show as a error in the taskcat report so build processes will see that as a failure
> 
> * Taskcat Version 0.8.19

**Comment by agamzn** [comment]
Depends on the fix in #195

**Comment by andrew-glenn** [comment]
If a stack enters a CREATE_FAILED state, we exit w/a non-zero exit code. Build systems should look at this exit code and *not* the output.
