### ISSUE TITLE
Testcase directories structure documentation defect

### ISSUE THREAD

**Issue by viralmutant** [aws-quickstart/taskcat#25]
I noticed that the ASCII art depicting the directory structure on the main page under the heading
> Example of project directory structure

shows that all the directories - scripts, templates, submodules etc. should be placed as subdirectories of 'ci'
However the testcase example directory has all of them at the same level as 'ci'.

I haven't tested if it works by placing everything under 'ci' too but this is a mismatch in the doc v/s example

**Comment by avattathil** [comment]
thanks for reporting   (Below is the corrected dir structure) 
```sample-cloudformation-project/
    ├── LICENSE.txt
    ├── README.md
    ├── ci
    │   ├── config.yml <- This the config file that will hold all the test definitions
    │   ├──  sample-cloudformation-input-novpc.json <-  This file contain input that will pass in during stack creation [vpc version] (See auto parms for more info)
    │   ├──  sample-cloudformation-input-withvpc.json <-  This file contain input that will pass in during stack creation [no-vpc version](See auto parms for more info)
    ├── scripts
    │   └── userdata.sh <- If you have userdata scripts you can load then in the scripts directory
    ├── submodules  <- If you have git submodules you can load them in the submodules directory
    │   └── quickstart-aws-vpc
    │       └── templates
    │           └── aws-vpc.template
    └── templates
        ├── sample-cloudformation-project-novpc.template
        └── sample-cloudformation-project-withvpc.template <- Second version on template that will create a vpc with the workload```

**Comment by avattathil** [comment]
@viralmutant  Updated https://aws-quickstart.github.io/taskcat/

Thanks
--Tony

**Comment by viralmutant** [comment]
Minor comment. Should not this one

> ├──  sample-cloudformation-input-withvpc.json

be replaced with ?

> └──sample-cloudformation-input-withvpc.json

**Comment by avattathil** [comment]
Updated
