### ISSUE TITLE
No Script examples

### ISSUE THREAD

**Issue by nampatra** [aws-quickstart/taskcat#26]
Please provide some examples for scripts as currently there are none.

**Comment by avattathil** [comment]
The script directory holds the scripts used with in userdata or cfninit
Here are some examples:
https://github.com/aws-quickstart/quickstart-hashicorp-nomad/tree/develop/scripts
https://github.com/aws-quickstart/quickstart-linux-bastion/tree/develop/scripts
taskcat and quickstart platform will upload the scripts/submodule and templates directory to s3 so  it can be referenced like this: 
https://github.com/aws-quickstart/quickstart-hashicorp-nomad/blob/develop/templates/quickstart-hashicorp-nomad.template#L495
or
https://github.com/aws-quickstart/quickstart-linux-bastion/blob/develop/templates/linux-bastion.template#L618

**Comment by avattathil** [comment]
If you need more help you can reach me at tonynv@amazon.com
