### ISSUE TITLE
Redirect Logs to specific folder

### ISSUE THREAD

**Issue by tbulding** [aws-quickstart/taskcat#266]
Would it be possible to add a switch in TC to direct the output logs to a specific folder.
example:
`taskcat -c /Users/jdoe/qs/myqs/ci/taskcat.yml -P jdoe -n -L /Users/jdoe/qs/logs/`
Where -L represents the switch for Logs

**Comment by andrew-glenn** [comment]
https://github.com/aws-quickstart/taskcat/blob/d7dc2eb3c3e6bf0ab14355c3c1841ed15b886444/taskcat/_cli_modules/test.py#L97-L101
