### ISSUE TITLE
New Flag: remove public s3 permissions after test

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/taskcat#272]
- Regardless of cleanup setting, we should remove public permissions from an autobucket if <flag> is set. 

I think this should be a long-form flag --public-s3-perm-removal, or similar.

**Comment by jaymccon** [comment]
Do we need a flag ? haven't looked at what the current behavior is but defaulting to a private bucket seems sensible, and perhaps provide a flag or config option to enable either public objects or public bucket.

**Comment by andrew-glenn** [comment]
We have a flag to enable public objects/bucket. The flag aside, I'm proposing we revoke those public permissions after the stack create is complete.

**Comment by andrew-glenn** [comment]
This is the default behavior already; closing.
