### ISSUE TITLE
Linter fails when template file is produced by CF CLI package

### ISSUE THREAD

**Issue by e14nielson** [aws-quickstart/taskcat#278]
**Describe the bug**
I am working with nested CF templates where the children have a dependency order

**To Reproduce**
1. create child template
2. create parent template
3. call CF CLI package like this 
aws cloudformation package \
  --profile ${deploy_profile} \
  --region ${region} \
  --template-file ${parent} \
  --s3-bucket ${bucket} \
  --output-template-file package-template.yaml
4. create config with scenario like this:
    test-scenario1:
      parameter_input: main_input.json
      template_file: package-template.yaml
5. call taskcat on config yaml like this:
taskcat -c ci/taskcat.yml -l

**Expected behavior**
package-template.yaml contains the child stack with a url like this:
TemplateURL: https://s3-us-west-2.amazonaws.com/${bucket} /bdf00048d714640fe19dfe960994b09f.template
where it was uploaded.

Taskcat should be able to pull the child from the url to lint

INSTEAD i get:

[ERROR  ] :Linter failed to load template /Users/ericnielson/Source/temp/deployment/${bucket} /bdf00048d714640fe19dfe960994b09f.template "[Errno 2] No such file or directory: '/Users/ericnielson/Source/temp/deployment/${bucket} /bdf00048d714640fe19dfe960994b09f.template'"

Why is it looking in WorkingDir/${bucket} ?

**Comment by jaymccon** [comment]
At present taskcat doesn't fetch child templates from s3 and as you have observed expects any child templates to be present in the local working folder. 

We plan on reworking how child template relationships are done in the next major release, although I'm not sure that the example you provided will be supported as it would involve resolving ${bucket} which may not be possible due to linting happening before the stack is deployed

**Comment by e14nielson** [comment]
${bucket} is being populated fine i just didnt want to include specific bucket names.

To be clear: next major release will properly reference child s3 template urls?

timeline?

thanks,

**Comment by jaymccon** [comment]
next release will have better handling of template relationships, not certain if that will include support for fetching child templates from S3 though (especially if the url contains references) although with a good use-case I'd be happy to add it to the 0.9 feature requirements. At present there is no timeline for release, best I can offer is that it is being worked on, but is not close to completion.

The problem with resolving references is that this is done by CloudFormation at runtime when you issue a stack create. Linting is done prior to the stack being launched, so the relationship is just not there. 

If the source of `${bucket}` happens to be a `Parameter` which either has a default, or the value is specified in a taskcat parameter file, then with some extra work we can resolve the full value of the parameter, to get an actionable s3 URL to fetch from, if the value is derived from another resource (ie. you have an s3 bucket in the template with the logical name `bucket`) then we cannot derive the value without first launching the stack.

Is this template part of your project (so in your working folder somewhere) or is it a 3rd party/remote only template ?

**Comment by e14nielson** [comment]
the CF CLI package resolves all references so the package template is complete but references S3

main.yaml contains child stack resources that have something like TemplateURL: templates/child_cft.yaml

if i try taskcat on main.yaml it produces an error like: TemplateURL must be an Amazon S3 URL.

i then run:
aws cloudformation package 
--profile ${deploy_profile} 
--region ${region} 
--template-file main.yaml
--s3-bucket ${bucket} 
--output-template-file package-template.yaml

package-template.yaml contains child stack resources that have something like TemplateURL: https://s3-us-west-2.amazonaws.com/cf-templates-11k8r86mqrbm-us-west-2/0ec218a82b9139ec30207f921032c76b.template

now if i try taskcat on package-template.yaml it produces an error like: [ERROR  ] :Linter failed to load template /Users/ericnielson/Source/temp/deployment/cf-templates-11k8r86mqrbm-us-west-2/0ec218a82b9139ec30207f921032c76b.template "[Errno 2] No such file or directory: '/Users/ericnielson/Source/temp/deployment/cf-templates-11k8r86mqrbm-us-west-2/0ec218a82b9139ec30207f921032c76b.template'"

So you see it tells me it needs to be an S3 URL but then it doesnt work with the S3 URL

**Comment by andrew-glenn** [comment]
@e14nielson  - Understood. I think basic support for TemplateURLs is a good idea, and I _think_ it shouldn't be too difficult to add functionality for your use case. As Jay mentioned, it becomes tricky when variables are introduced, but that's not the case here. 

Let me see what I can come up with. I don't have a timeline either, but the goal is to add this to a 0.8.x release vs 0.9.x. Leaving this thread open for tracking.

**Comment by e14nielson** [comment]
@andrew-glenn @jaymccon Thanks to both of you. It sounds like i am using it correct and that this is something that will need to be added. I might pull the code as well and see if i can help contribute.

**Comment by zaro0508** [comment]
I'm running in this issue as well.  Is there a way to either disable the linter when running taskcat or ignore this failure?  I just want a work around until this issue is resolved.

**Comment by andrew-glenn** [comment]
@e14nielson @zaro0508  - In doing housekeeping, we're unable to see where an exception is raised that would cause taskcat to exit out. Can you provide more context around the error message so we can track down where this is coming from?

**Comment by e14nielson** [comment]
@andrew-glenn 

sure, many of my more complex deployments rely on nested stacks. this means i have a main.yaml whose resources are of type: AWS::CloudFormation::Stack.

in my templates directory i have several yaml files which are referenced locally from the main.yaml like this:

  MyResource:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../templates/resource_cft.yaml
      Parameters: ...

if my taskcat.yml file contains:
tests:
  test-main:
    parameter_input: input.json
    template_file: main.yaml
 
when i call: taskcat -c ci/taskcat.yml -P ${profile}
linting succeeds but deployment fails with:
"TemplateURL must be an Amazon S3 URL" from CloudFormation
on every resource in main.yaml.

if i run:
aws cloudformation package --region ${region} --template-file templates/main.yaml --s3-bucket ${templates_bucket} --s3-prefix ${stack_name} --output-template-file package-template.yaml --profile ${profile}

and taskcat.yml is like:
tests:
  test-main:
    parameter_input: input.json
    template_file: package-template.yaml

linting will fail on all resource in main 
Linter failed to load template /Users/ericnielson/Source/MyDataPlatform/DataPlatform/caec2627f0b6bd42d09bedf745246acb.template
as this is the S3 URL, but deployment succeeds. (note: linting failed but didnt fail the process or exit with an error code)

If i add
aws s3 cp s3://${templates_bucket}/${stack_name} ./${stack_name} --recursive --profile ${profile}
to download all the deployment packages from the package command locally then lint and deployment succeed. meaning the lint will work again the local templates and deployment work off the s3 templates.

Expectations i would hope for from task cat.
1. if linting fails it should exit with an error code (https://github.com/aws-quickstart/taskcat/issues/279)
2. taskcat should be able to gather all child templates for deployment without needing multiple CLI commands to work around this issue.

**Comment by andrew-glenn** [comment]
@e14nielson  - Thanks for the clarification! 

In v0.9, we'll be adding strict linting, which will resolve #279. @jaymccon  and I will have further discussions around child-template relationships and so forth. For the moment, I defer to his earlier commentary in March. 

I'm leaving this open so we can continue to track.

**Comment by e14nielson** [comment]
@andrew-glenn this sounds great as i am found a workaround. thank you

**Comment by zaro0508** [comment]
@andrew-glenn would you mind sharing your workaround because I still have tests commented out due to this issue.

**Comment by andrew-glenn** [comment]
@e14nielson ^^

**Comment by e14nielson** [comment]
@zaro0508 i think you meant to refer to me as i have the work around. please see my earlier post today about taskcat requiring both a local and s3 url of the .template files created by the cli package command. this will allow the lint and deployment to work.

**Comment by WowKapz** [comment]
Hi @e14nielson can you please tell me the step by step solution that you are earlier referring in this online discussion.

I am getting similar error as
![image](https://user-images.githubusercontent.com/22850489/67856329-496bfe80-fb3a-11e9-9cda-503e2b294324.png)

Please help me to solve this @e14nielson

**Comment by ekzGuille** [comment]
I'm very interested in this feature. 
My main.template.json has 3 AWS::CloudFormation::Stack with an existing S3 as TemplateURL.
When I launch `taskcat test run` linter is warning about:
`Failed to discover path for (S3 Nested  Stack 1 template path), path (Local Nested Stack 1 template path) does not exist`.
(And same error for the remaining 2 Nested Stacks)

Otherwise lint for main.template.json passes successfully and start uploading templates to temp S3
but *CREATED_FAILED* error appears with the reason:
[INFO   ] : The following resource(s) failed to create: [_NestedStack1_, _NestedStack2_,
_NestedStack3_].

* Taskcat version: 0.9.8
* Installation method: pip3

**Comment by nfairoza** [comment]
I am having the same issue. with 0.9.8 taskcat. I have checked yaml lint, th yaml is valid and all paths are correct.

**Comment by tonynv** [comment]
Path discovery is not supported for all path styles. For this to work correctly path style must match discovery logic
