### ISSUE TITLE
Request: Do not hard-code paths

### ISSUE THREAD

**Issue by jamestharpe** [aws-quickstart/taskcat#282]
Taskcat requires certian directories, such as `templates/` and `ci/`, to exist. It would be nice if such paths were NOT hard-coded and, instead, were simply part of the configuration.

**Comment by andrew-glenn** [comment]
This is something we've been targeting internally ourselves as well. It's on our radar, and has been added to the v0.9 roadmap.

**Comment by andrew-glenn** [comment]
This is addressed in v0.9.0
