### ISSUE TITLE
ClientFactory to support regional STS Endpoints

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/taskcat#289]
STS is now a regional-endpoint based services. Our calls to STS clients should reference a specific region rather than rely on the global endpoint.

**Comment by jaymccon** [comment]
Where are you picking up calls to the global endpoint? I don't see any calls to sts in client_factory.py and the only place I find sts is called in taskcat seems to already specify a region for the client.

https://github.com/aws-quickstart/taskcat/blob/b1316ff5c7bddcccd24091e7bad50163538505a0/taskcat/stacker.py#L1334-L1336

**Comment by vsnyc** [comment]
That may or may not work, but the [documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html) states the following:

AWS STS recommends that you use both the setRegion and setEndpoint methods to make calls to a Regional endpoint. You can use the setRegion method alone for manually enabled Regions, such as Asia Pacific (Hong Kong). In this case, the calls are directed to the STS Regional endpoint. To learn how to manually enable a Region, see Managing AWS Regions in the AWS General Reference. If you use the setRegion method alone for Regions enabled by default, the calls are directed to the global endpoint of https://sts.amazonaws.com.

**Comment by vsnyc** [comment]
Just tested it as well, you do need the endpoint. See snippet below.

```
>>> import boto3
>>> sts1 = boto3.client('sts', region_name='us-west-2', endpoint_url='https://sts.us-west-2.amazonaws.com')
>>> sts2 = boto3.client('sts', region_name='us-west-2')
>>> print(sts1._endpoint)
sts(https://sts.us-west-2.amazonaws.com)
>>> print(sts2._endpoint)
sts(https://sts.amazonaws.com)
```

**Comment by jaymccon** [comment]
Thanks for the research @vsnyc. Let's look at patching for now, even though, imho, intricacies like this should be handled in boto3/botocorr

**Comment by jaymccon** [comment]
https://github.com/boto/boto3/issues/1859

https://github.com/boto/boto3/issues/1939

**Comment by jaymccon** [comment]
we'll need to discover the endpoint url (seeing as it differs for some partitions) and sadly there doesn't seem to be a direct public method for this https://github.com/boto/boto3/issues/1166

**Comment by jaymccon** [comment]
quick attempt at a generic endpoint finder function:

```
import botocore.loaders
import botocore.regions
def get_endpoint_for_s3_bucket(service, region):
    loader = botocore.loaders.create_loader()
    data = loader.load_data("endpoints")
    resolver = botocore.regions.EndpointResolver(data)
    endpoint_data = resolver.construct_endpoint(service, region)
    return f"https://{endpoint_data['hostname']}"
```

**Comment by andrew-glenn** [comment]
@jaymccon  - Thanks. I'll be working on the PR within the coming days. That helps get me off the ground.

**Comment by andrew-glenn** [comment]
This issue is now slated for the v0.9 branch.
