### ISSUE TITLE
Re: Using Taskcat it is creating every time new stacks

### ISSUE THREAD

**Issue by ravitejac** [aws-quickstart/taskcat#290]
Hi,

In AWS codepipeline, we are using taskcat to deploy application but it is creating every new stacks. 
How to update stack if it already exists? Can you please help me out of this issue or links to solve the problem.

**Comment by andrew-glenn** [comment]
@ravitejac  - Taskcat is currently designed to perform the behavior you're seeing. However, we're happy to consider this a feature request. 

The biggest blocker here is a way to track previously launched CFN Stacks. Would your workflow be open to either a tag on the taskcat-launched-stacks, or perhaps a DynamoDB table?

**Comment by jaymccon** [comment]
In CodePipeline the native CloudFormation integration already handles create/update. Id' be interested to know what existing features in taskcat are prompting it's use over the native integration. 

Oh, and this feature is on the roadmap for the next taskcat major release https://github.com/taskcat/taskcat-v9/issues/12

**Comment by LackoDan** [comment]
Also looking forward to this. I'm looking into deploying CloudFormation templates from Jenkins, and taskcat would be ideal if we could use it to test stack updates.

**Comment by tonynv** [comment]
Archiving.. This is not in scope for v0.9 (Closing)
