### ISSUE TITLE
AMIUpdater reports ap-northeast-3 as invalid region

### ISSUE THREAD

**Issue by villasv** [aws-quickstart/taskcat#291]
**Describe the bug**
Despite Amazon Linux 2 clearly offering images for the ap-northeast-3 region (as documented [here](https://aws.amazon.com/amazon-linux-2/release-notes/)), having it on a region mapping will make AMIUpdater fail.

**To Reproduce**
1. Add `ap-northeast-3` to mappings region
2. Run AMIUpdater

**Expected behavior**
Run without errors

**Version (Please make sure you are running the latest version of taskcat)
 - 0.8.35

 Note: Python Version 3.6.6

**Comment by andrew-glenn** [comment]
@villasv - Thanks for leveraging AMIUpdater. Would you mind sending me an email (andglenn@amazon) so I can better understand how you're using it? 

To the issue at hand... I'll check this out today and return back. I need ☕️  first. :)

**Comment by andrew-glenn** [comment]
@villasv  - AMIUpdater does an `ec2.describe_regions` call to get a list of regions that are "valid". WIthout access to the region, updating the AMIs is moot. 

Can you confirm that `ap-northeast-3` is in your describe-regions call? 

Even so, I can handle this better in the function. Thinking over that now. 

https://github.com/aws-quickstart/taskcat/blob/b1316ff5c7bddcccd24091e7bad50163538505a0/taskcat/amiupdater.py#L302-L320

**Comment by villasv** [comment]
Indeed, ap-northeast-3 doesn't show up:

```python
>>> import boto3
>>> client = boto3.client('ec2', 'us-east-1')
>>> print('\n'.join([r['RegionName'] for  r in client.describe_regions()['Regions']]))
eu-north-1
ap-south-1
eu-west-3
eu-west-2
eu-west-1
ap-northeast-2
ap-northeast-1
sa-east-1
ca-central-1
ap-southeast-1
ap-southeast-2
eu-central-1
us-east-1
us-east-2
us-west-1
us-west-2
```

**Comment by andrew-glenn** [comment]
@villasv  - Cool. So in these situations, what would be your desired behavior? I can skip over the region if it's not in the list and print a warning. 

Would that work for you?

**Comment by villasv** [comment]
Hmm, it seems this is intentional from the AWS team: https://github.com/aws/aws-sdk-go/issues/1863

> I researched this issue, and this region is intentionally excluded for all of the SDKs and Tools as ap-northeast-3 requires access request.

So I guess we should trust the current method of retrieving supported regions.

**Comment by villasv** [comment]
I'm in for closing the issue as it's not a problem with taskcat, but a region that has special behavior. It's enough to just have this documented here.

**Comment by andrew-glenn** [comment]
@villasv  - Fair enough. I debated on throwing an exception or a warning. I was concerned though that simply printing a warning would mean automated pipelines would fail silently without a Human checking on it.
