### ISSUE TITLE
AMIUpdater replacement affects unwanted portions of the template

### ISSUE THREAD

**Issue by villasv** [aws-quickstart/taskcat#292]
**Describe the bug**
If I add a region to my mapping and initialize it with something like `ami-0`, AMIUpdater will replace all occurrences of `ami-0` with the new AMI, which will mess up all other AMIs because they all start with `ami-0`.

**To Reproduce**
1. Change one of the AMIs to `ami-0` (or any prefix that maches multiple AMIs)
2. Run AMIUpdater

**Expected behavior**
Only the value inside that region should be changed, not values for other regions.

**Version (Please make sure you are running the latest version of taskcat)
 - 0.8.35

 Note: Python Version 3.6.6

**Comment by andrew-glenn** [comment]
@villasv 

After the latest AMI ID has been identified, I replace all instances of the "old" ID in the template using regular expressions. The original thought was that this would address AMI IDs that were hardcoded outside of the mapping section. 

However the value you use to initialize the mapping is considered the "old" AMI too.  I think a better approach is to isolate the find/replace to the Mapping by default, and allow an 'expert mode' flag if someone wants to use it. 

I've been working on something else that will make this much easier to accomplish. I'm investigating how much effort it'll take to implement this. 

In the interim, I recommend initializing the mapping values with UUIDs or a similar value that doesn't exist elsewhere in the template.

**Comment by villasv** [comment]
Cheers, it's not a blocking issue. Running AMIUpdater a second time will fix the IDs it messed in the previous run. But I agree that replacing in the whole document should be an optional behavior and the default only updates the mapping without needing a search and replace.

The only case that requires manual intervetion is initializing multiple AMI IDs with the same value. AMIUpdater will treat those as the same region, so initial values must be different.

**Comment by andrew-glenn** [comment]
@villasv  - Cool. I'll see what I can knock out

**Comment by jaymccon** [comment]
to add some clarity on why search and replace is being used, roundtripping yaml/json results in broad changes to the source template formatting which we deemed undesirable.
