### ISSUE TITLE
DeprecationWarning: You are using the get() function from 'botocore.vendored.requests'.

### ISSUE THREAD

**Issue by magic7s** [aws-quickstart/taskcat#318]
**Describe the bug**
`
DeprecationWarning: You are using the get() function from 'botocore.vendored.requests'.  This is not a public API in botocore and will be removed in the future. Additionally, this version of requests is out of date.  We recommend you install the requests package, 'import requests' directly, and use the requests.get() function instead.
`

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*?
2. Attach or link a copy of the template if possible (**remove any sensitive info**)
3. Provide the parameters that you passed. (**remove any sensitive info**) 
4. How did you install taskcat? (docker or pip3) pip3
5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat?
6. Is your AWS environment configured via `aws configure`?

**Expected behavior**

**Screenshots**

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (ex: [2018.817.210357])

 Note: Python Version (python3 required)

To find versions:
*Via taskcat*: `taskcat -V`
*Via pip3*: `pip3 show taskcat`

Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by andrew-glenn** [comment]
https://github.com/aws-quickstart/taskcat/blob/0d5004f00303008bb1aec7e7af9de44a8e73a4da/taskcat/stacker.py#L39

https://github.com/aws-quickstart/taskcat/blob/0d5004f00303008bb1aec7e7af9de44a8e73a4da/taskcat/generate_reports.py#L4

This likely won't be addressed until v0.9 branch (we're relatively close). I'm adding the relevent v0.9 issues as related items so we can fully track.

**Comment by andrew-glenn** [comment]
Report Generation: 
- https://github.com/taskcat/taskcat-v9/issues/2

Stacker:
- https://github.com/taskcat/taskcat-v9/pull/41

**Comment by jaymccon** [comment]
> Report Generation:
> 
> * [taskcat/taskcat-v9#2](https://github.com/taskcat/taskcat-v9/issues/2)
> 
> Stacker:
> 
> * [taskcat/taskcat-v9#41](https://github.com/taskcat/taskcat-v9/pull/41)

not importing requests from botocore anywhere in this pr 😺

**Comment by andrew-glenn** [comment]
Fixed by #343
