### ISSUE TITLE
Feature Request: Optional Stack Role ARN Parameter

### ISSUE THREAD

**Issue by giles-jason** [aws-quickstart/taskcat#323]
Something that would be extremely helpful was if taskcat supported passing a stack role to be used when creating test stacks. 

When deploying CloudFormation stacks in a CodePipeline, the stack role is a required parameter. This can lead to some interesting issues where taskcat can pass its tests, but the deployment can fail due to subtle differences in the roles between the two. Additionally, it would be nice to limit the permissions given to the CodeBuild project running taskcat, but allow it to pass a role to CloudFormation for the test stacks.

**Comment by zetas** [comment]
I really can't believe this is not supported, I guess we are edge cases @giles-jason. I scoured the source code but `role_arn` is not set anywhere for the stack, this is required for our testing pipeline to also test the "run as role" functionality as this is our default deployment to our customers. 

In case anyone wants to know what we're talking about: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Stack.role_arn

**Comment by andrew-glenn** [comment]
@zetas 

Thanks for bubbling this back up to the surface. I was able to dedicate some cycles to this today. My draft PR is https://github.com/aws-quickstart/taskcat/pull/534 .
