### ISSUE TITLE
Feature Request: Add "Delete Retry #"

### ISSUE THREAD

**Issue by magic7s** [aws-quickstart/taskcat#324]
**Situation:** Currently a failed deployment will revert and delete the stack. If the delete fails, there is no retry available.  Some resources cannot be deleted immediately after creation (i.e. ElasticCache). But a delete a few minutes later will succeed. 

**Impact:** A failed delete requires manual login to every region and clicking delete stack after it has completely failed. All resources dependant on the failed to delete element will fail to delete as well (i.e. Subnets, VPC, etc). This can lead to stale resources being charged until manual deletion. 

**Example Error:**
```
Cache cluster tcc5lx4arp18ldj-002 is not in a valid state to be deleted. (Service: AmazonElastiCache; Status Code: 400; Error Code: InvalidReplicationGroupState; Request ID: abbc6264-8bdd-47e9-adf9-f53208cccc61)
```

**Comment by andrew-glenn** [comment]
@magic7s  - Thanks. I'm tagging this for v0.9.0 for now until we have a chance to discuss where this fits into our roadmap a bit further.

**Comment by andrew-glenn** [comment]
No plans to implement. Closing.
