### ISSUE TITLE
Question: Running only selective tests

### ISSUE THREAD

**Issue by lavk7** [aws-quickstart/taskcat#338]
**Describe the bug**
This is not a bug. I want to confirm whether I can run tests selectively in TaskCat

For example, I have the following taskcat.yml
```!yaml
---
global:
  owner: owner@company.com
  qsname: sample-taskcat-project
  regions:
    - ap-southeast-1
tests:
  first-test:
    parameter_input: debug-input-1.json
    regions:
      - ap-southeast-1
    template_file: cloudfront.yml
  second-test:
    parameter_input: debug-input-2.json
    regions:
      - ap-southeast-1
    template_file: s3.yml
```

Is there any way I can just run the first test, for example like this:
```
taskcat -c ci/taskcat.yml -m first
```

I want to use this functionality because I have to test many individual components of AWS using CloudFormation, but I do not want to make `taskcat.yml` for every component. So let me know if this feature exists already or any reasoning for this not being required.
Thanks in advance

**Comment by andrew-glenn** [comment]
@lavk7 - at the moment, this feature doesn't exist. We're in the last stages of our 0.9.x release branch, and I anticipate this (or equivalent) would be available in 0.9.1 or perhaps a little later.

**Comment by lavk7** [comment]
@andrew-glenn  Got it. 
Writing a secondary config file is what I have been doing for now. Well, I'll wait for it then.
Thanks for the quick response.

**Comment by andrew-glenn** [comment]
This was added via https://github.com/aws-quickstart/taskcat/pull/525. It's available in our current development release, and will be in `0.9.18`. 

If you're interested in the dev release:

`pip install taskcat==0.9.18.dev3`
