### ISSUE TITLE
Stacker doesn't validate that key found in metadata explicitly matches project prefix.

### ISSUE THREAD

**Issue by agamzn** [aws-quickstart/taskcat#36]
The stacker module does fuzzy matching on the prefix from the bucket object metadata. This leads to unexpected results when multiple prefixes match what's in the taskcat config. 

More validation is needed to ensure only the keys with the prefix *explicitly* matching the config variable are used to generate the template URL. 

Examples are sanitized, but this is a duplicate of the stacker module, lines 407-412 (get_s3_url function).  The only difference is this, for debugging purposes.
```
foo.append(metdata[1])
```
/////
```python
>>> for s3obj in contents:
...     for metadata in s3obj.items():
...             if metadata[0] == 'Key':
...                     if key in metadata[1]:
...                             foo.append(metadata[1])
... 
>>> foo
['example.old/LICENSE.txt', 'example/LICENSE.txt']
```

PR Forthcoming.

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/taskcat/commit/7360917585f5a0f24027259950cbd82c344f0aa1
