### ISSUE TITLE
Shortening stack names generated by taskcat

### ISSUE THREAD

**Issue by villasv** [aws-quickstart/taskcat#360]
This isn't really a bug, but it's something that I've been struggling a few times already. With v0.9 the naming scheme for stacks apparently got even more verbose, now including bits of the project name and a longer hash.

Testing with taskcat generates unusually long stack names. For instance, the one I just launched is:

```
tCaT-quickstart-turbine-airflow-master-5ca6fef18a584f548887d137538568ba
```

(for reference, v0.8 usually gave me something like `tcat-tag-default-f2469890`)

And in my particular case, I have a few nested stacks with default naming, which yields names like:

```
tCaT-quickstart-turbine-airflow-master-5ca6fef18a584f548887d137538568ba-AirflowStack-4FCMXM3HHUHR
```

And this is long enough to break stuff if I use names like `${AWS::StackName}-deployment-application`, because of `CloudDeploy`'s limit of 100 characters for application names.

I've been having problems also for SQS queue names being too long, even bumping up on certain libraries like Celery and Airflow for not being prepared for ridiculously long names for configuration items.

What would be the recommended workaround? The only option I've imagined so far is to really stop using `StackName` as prefix for resources, but that's very useful in production :-/

**Comment by villasv** [comment]
If avoiding the use of `StackName` as prefix for stuff is the only way, I'm not going to be mad. But I'd recommend that observation in the QuickStart guidelines so people can start off with the right mindset instead of having to migrate dozens of resources like I am right now ;-)

**Comment by andrew-glenn** [comment]
@villasv The current recommendation is to avoid the stack name as a prefix/suffix. However, I think there's work we can do here. Maybe a few configuration options that allow you to shorten the stack name? _(With a warning that name collisions may occur, so be careful)_

Given:

`tCaT-quickstart-turbine-airflow-master-5ca6fef18a584f548887d137538568ba`

Without looking at the schema and determining how much effort his would really be, I can see a project level config with these options

```
short_project_name="airflow-master"
uuid_length=4
```

The end stack-name would be...

`tCaT-airflow-master-5ca6`

Would that point you in the right direction? 

_Edit: Markdown formatting_

**Comment by avattathil** [comment]
@villasv to your point i thing it’s better to avoid a pattern like, using `stackname` embedding in resource names. 

To identify resources it always better to tag the resource and have CFN generate the name. (where possible) 

Would providing a unique id parameter in your templates and passing a taskcat random string be a suitable option instead of going down this path?

**Comment by villasv** [comment]
> @andrew-glenn 
> Would that point you in the right direction?

It most definitely would.

> @avattathil

My first issue with long names was exactly because I was trusting CFN to generate names. I have three layers of nested stacks, and their names are automatically generated. They're inevitably long.

And in deep inside the stack I had an SQS Queue, which also autogenerates the with the stack name as prefix. And like I said, this is the norm for other services as well (AFAIK ECS and ALB).

So I can improve my situation if I avoid using StackName as prefix where I can, but in a few places this is the standard behavior.

**Comment by villasv** [comment]
Another suggestion: since taskcat already tags the template with the project info, given
```
tCaT-quickstart-turbine-airflow-master-5ca6fef18a584f548887d137538568ba
```
shortened to 
```
tCaT-5ca6fe
```

would suffice to me.

**Comment by villasv** [comment]
Now I can use `shorten_stack_name: true` and test stack names are close to the common usage.

**Comment by ozbillwang** [comment]
this is real help to create `shorten_stack_name: true`

I don't see anything wrong to use `${AWS::StackName}` as part of resource name. In fact, It is a good design, that we easily deploy the same template to different environments, with just change the `stackname`
