### ISSUE TITLE
Not able to generate a password with symbols

### ISSUE THREAD

**Issue by skellish-aws** [aws-quickstart/taskcat#39]
Running taskcat version 2017.821.154206
Docker version 17.06.1-ce, build 874a737

my parameter file has following:
{
    "ParameterKey": "AdminPassword",
    "ParameterValue": "$[alfred_genpass_32S]"
}
When I run the test locally on my mac, getting error:

[ERROR  ] :An error occurred (ValidationError) when calling the CreateStack operation: Parameter DBMasterUserPassword failed to satisfy constraint: Must be at least 8 characters containing letters, numbers and symbols.

I pulled out and debugged the password generation code itself (see attached x.py) and see this:

param_value=$[alfred_genpass_32S]
passlen=32
gentype=a
[DEBUG  ] :AutoGen values for $[alfred_genpass_32S]
[DEBUG  ] :Auto generating password
[DEBUG  ] :Pass size => 32
[DEBUG  ] :Pass type => default alpha-numeric
param_value=rP7dK5aX7aJ6vB4mS9hS1wL5eQ7nJ5uE4

The gentype detected is 'a'.

Looking at the gentype_re, I see that re us matching the first 'a' (in alfred) and using that:

![image](https://user-images.githubusercontent.com/25795804/29624961-6dc0b846-87f8-11e7-8b60-8452e1a98a50.png)

[test.zip](https://github.com/aws-quickstart/taskcat/files/1246057/test.zip)

![image](https://user-images.githubusercontent.com/25795804/29624914-57304056-87f8-11e7-92ea-1b35b804b730.png)

**Comment by sshvans** [comment]
Fixed a125d6e9566392e78c4cd2fa94381c8a9cba2e9e
