### ISSUE TITLE
Auto-gen'd S3 bucket not deleted after run

### ISSUE THREAD

**Issue by skellish-aws** [aws-quickstart/taskcat#40]
Taskcat is not removing the S3 bucket at the end of the test if --no_cleanup is not specified

**Comment by avattathil** [comment]
@skellish-aws Please provide some clarification.  Is it a bucket that was created as part of the CFN template or are you referring to the bucket created by `$[taskcat_autobucket]`

**Comment by avattathil** [comment]
@skellish-aws any updates here?

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/taskcat/commit/a62dc91706aa605777e912b8286efe73d9419575
