### ISSUE TITLE
Feature Request: Expose `stack_name_prefix` as config option

### ISSUE THREAD

**Issue by dylanvaughn** [aws-quickstart/taskcat#418]
Hello!  I'm working to integrate TaskCat into an AWS account which is used by multiple teams.

We scope permissions related to CloudFormation stack creation / deletion to prefixes of the stack name.  It would be helpful for us if we could configure the default `stack_name_prefix` that is shipped with TaskCat here:

https://github.com/aws-quickstart/taskcat/blob/a7a08f7cd567d357468f8cfbff38bd8845611695/taskcat/_cfn/threaded.py#L37

in the `.taskcat.yml` config somehow.

Thanks, Dylan

**Comment by andrew-glenn** [comment]
@dylanvaughn - Bummer that Cloudformation:DeleteStack doesn't support tags. We're tagging this for the next point-release.

**Comment by andrew-glenn** [comment]
Cross-post: #562
