### ISSUE TITLE
Taskcat crash when create nested Stack version:0.9.7

### ISSUE THREAD

**Issue by kokosandim** [aws-quickstart/taskcat#423]
When I give one template to taskcat, it works well.
But if I test Nested stacks taskcat all-time shows error "TypeError string indices must be integers"
![image](https://user-images.githubusercontent.com/12952533/69254499-10fe9400-0bbf-11ea-952a-999001b84b35.png)

Has anyone encountered this problem?

**Comment by jaymccon** [comment]
@kokosandim are you able to provide some sample templates I could use to reproduce ?

**Comment by jaymccon** [comment]
@kokosandim will cut a release containing the fix for this shortly.

**Comment by kokosandim** [comment]
Ok, great! If I can help you, let me know

**Comment by kokosandim** [comment]
Thank you for your Great works!
