### ISSUE TITLE
UnboundLocalError local variable 'template_path'

### ISSUE THREAD

**Issue by aagarw0** [aws-quickstart/taskcat#429]
**Describe the bug**
When using the version 0.9.x of taskcat, taskcat is still looking for variable 'template_path' which exists in the old versions. When taskcat is run with new configuration file I get below error:
UnboundLocalError local variable 'template_path' referenced before assignment

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*? *Custom template*
2. Attach or link a copy of the template if possible (**remove any sensitive info**) Can't attach the template but the taskcat is not even launching it so no point attaching. Use any template for testing.
3. Provide the parameters that you passed. (**remove any sensitive info**) Use any parameters.
4. How did you install taskcat? (docker or pip3)? *pip3*
5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat? *profile*
6. Is your AWS environment configured via `aws configure`? *yes*

**Expected behavior**
My project structure is as below:
[Project root]
- [templates]: contains cloudformation templates
- [ci]
  - [staging]
    - [.taskcat.yml]
    - [.taskcat_overrides.yml]
  - [prod]
    - [.taskcat.yml]
    - [.taskcat_overrides.yml]

Attached screenshot of file .taskcat.yml:
![image](https://user-images.githubusercontent.com/50673357/69547492-b482e680-0fbb-11ea-91ba-176aaa196105.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/50673357/69546889-95d02000-0fba-11ea-9f8b-7cf04cc55441.png)

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version 0.9.1, 0.9.8

 Note: Python Version (python3 required) 3.7

P.S: I am new to this so I might have not followed the standards that we are supposed to. Let me know and I will rectify.

**Comment by andrew-glenn** [comment]
Housekeeping: I believe this to be resolved in good faith. please reopen if this is still occuring.
