### ISSUE TITLE
HOWTO: pass a parameter in a command line

### ISSUE THREAD

**Issue by sumanth-lingappa** [aws-quickstart/taskcat#431]
Is there any way to pass a parameter in a command line to `taskcat test run`

Eg: `taskcat test run --parameter paramKey=paramValue`

This help in running takscat against a variable `paramValue `instead of manually changing the taskcat config files, everytime before run.

**Comment by andrew-glenn** [comment]
@sumanth-lingappa - Currently no. However we're happy to add it as a feature request.

**Comment by sumanth-lingappa** [comment]
Thank you for considering @andrew-glenn

**Comment by tonynv** [comment]
Archiving.. This is not in scope for v0.9 (Closing)
