### ISSUE TITLE
Is there an option where even thou taskcat execution fails at any point, it does a rollback

### ISSUE THREAD

**Issue by samy2019** [aws-quickstart/taskcat#436]
**Describe the bug**
Is there any option in cli, whenever taskcat fails, from that point of time onwards it does a rollover and deletes all the resources created SUCCESSFULLY.

**Comment by andrew-glenn** [comment]
Not at the moment, however we’re happy to add it as a feature request.

**Comment by andrew-glenn** [comment]
See #435 for context

**Comment by avattathil** [comment]
This seems like a connectivity issue.

**Comment by andrew-glenn** [comment]
After discussing this internally... there are already mechanisms in place to delete stacks. if there's an exception, taskcat is left in an unknown state. Deleting resources when we don't know the state of the utility could have unexpected results. 

For the time being, we prefer that github issues are raised if users experience an exception. In that case, users may need to manually clean up resources outside of taskcat.
