### ISSUE TITLE
Reconcile content from reinvent 2019 workshop

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/taskcat#437]
A lot of documentation improvements were made when creating the content for our workshop at re:invent 2019. It's time to bring that content back into this repo.

**Comment by andrew-glenn** [comment]
@sshvans  - can you take this on?

**Comment by sshvans** [comment]
@andrew-glenn Can you provide more detail? Happy to take on.

**Comment by andrew-glenn** [comment]
@sshvans - throughout https://taskcat.github.io/workshop/050_concepts/00_page2.html, we expanded detail on what various features do (lambda packaging, parameter generation, so forth).  The expanded documentation in our reinvent workshop (see link) needs to filter up to our generic taskcat docs.

**Comment by andrew-glenn** [comment]
@sshvans - any updates?

**Comment by andrew-glenn** [comment]
@sshvans 👻
