### ISSUE TITLE
ValidationError Additional properties are not allowed ('parameter_input' was unexpected)

### ISSUE THREAD

**Issue by zdlzhang** [aws-quickstart/taskcat#438]
I have many parametesr for aws-quickstart template, how to use json answer file for version 0.9.8?

**Comment by zdlzhang** [comment]
cat taskcat.yml
tests:
  2nodes:
    parameters: https://svcloud-travis.s3-us-west-2.amazonaws.com/2node_cfg.json

then hit another error:
[ERROR  ] : ValidationError 'https://svcloud-travis.s3-us-west-2.amazonaws.com/2node_cfg.json' is not of type 'object'

**Comment by andrew-glenn** [comment]
@zdlzhang, we've moved away from the json file in v0.9.x; However, we've put substansial effort into the migration path. Generally, if you run `taskcat test run -p /path/to/project` using v0.9.x, you'll see a `.taskcat.yml` generated in your project root. At that point, taskcat will use the new config file, and the old config files are ignored.

**Comment by zdlzhang** [comment]
@andrew-glenn Thank you very much, still need your help.
Does the file .taskcat.yml auto generate by taskcat?
Is there any way to use the function like parameter_input xx.json in v0.8.x?

**Comment by andrew-glenn** [comment]
@zdlzhang 

For migrating from 0.8.x -> 0.9.x, the .taskcat.yml *should* be generated by taskcat.
In 0.9.x, there's no parameter_input functionality at the moment - everything is in a single file.

What's your use case for a parameter input file in 0.9.x ? (NB: I understand you want it, I don't understand _why_ :) )

**Comment by andrew-glenn** [comment]
_Closing this issue for housekeeping purposes. Feel free to re-open if necessary_
