### ISSUE TITLE
ValidationError Additional properties are not allowed error. How to provide tags to template

### ISSUE THREAD

**Issue by nanda-suresh** [aws-quickstart/taskcat#442]
**Describe the bug**

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*?
2. Attach or link a copy of the template if possible (**remove any sensitive info**)
3. Provide the parameters that you passed. (**remove any sensitive info**)
4. How did you install taskcat? (docker or pip3)
5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat?
6. Is your AWS environment configured via `aws configure`?

**Expected behavior**

**Screenshots**

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (ex: [2018.817.210357])

 Note: Python Version (python3 required)

To find versions:
*Via taskcat*: `taskcat -V`
*Via pip3*: `pip3 show taskcat`

Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by andrew-glenn** [comment]
@nanda-suresh - We're happy to help, but there's no meaningful information here. Please provide your taskcat config file so we can better understand what you're trying to do. (It's also easier to provide examples with..)

**Comment by andrew-glenn** [comment]
No additional information has been provided. A bug was raised regarding tags, please see #449. Closing this issue.
