### ISSUE TITLE
taskcat pip package (update)

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/taskcat#47]
Update pip package so all assets and are packaged and deployed to 'bin' 
Simplify installer to `pip install taskcat`

**Comment by santiagocardenas** [comment]
Should we move all files into a /bin/ directory in the repo and remove the .py extensions? This just means that for local testing from GitHub repo clone, we have to create a copy outside so it uses the relative paths during import.

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/taskcat/commit/8e6f3a16786274b369cc11ad9dd8b67d732641af

Added [scripts] section to setup.py
