### ISSUE TITLE
Taskcat Error "ZoneId"

### ISSUE THREAD

**Issue by troy-ameigh** [aws-quickstart/taskcat#488]
**Describe the bug**
When running taskcat 9.12 or 9.13 I am getting the following error:
[ERROR  ] : KeyError 'ZoneId'

Regions: sa-east-1/ap-southeast-2 (possible in others)
project .taskcat.yml:

project:
  name: quickstart-fortinet-fortigate
  owner: dchao@fortinet.com
  package_lambda: false
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - ap-south-1
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1
  s3_bucket: ''
tests:
  quickstart-fortigate-test:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      BalanceWebTrafficOverPort: 443
      CustomIdentifier: fgtASG
      ExpireLifecycleEntry: '300'
      FortiGateAdminCidr: 10.0.0.0/16
      FortiGateAdminPort: '8443'
      FortiGateAsgCooldown: '300'
      FortiGateAsgDesiredCapacity: '2'
      FortiGateAsgHealthCheckGracePeriod: '300'
      FortiGateAsgMaxSize: '4'
      FortiGateAsgMinSize: '2'
      FortiGateAsgScaleInThreshold: '25'
      FortiGateAsgScaleOutThreshold: '80'
      FortiGateElbTgHealthyThreshold: '3'
      FortiGateInstanceType: c5.large
      FortiGatePskSecret: $[taskcat_genpass_8]
      InternalLoadBalancerDnsName: fgtqsg-asg
      InternalLoadBalancingOptions: add a new internal load balancer
      KeyPairName: taskcat
      PrivateSubnet1CIDR: 10.0.1.0/24
      PrivateSubnet2CIDR: 10.0.3.0/24
      PublicSubnet1CIDR: 10.0.0.0/24
      PublicSubnet2CIDR: 10.0.2.0/24
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-fortinet-fortigate/
      VPCCIDR: 10.0.0.0/16
    regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - ap-south-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-northeast-1
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    s3_bucket: ''
    template: templates/workload-master.template
  quickstart-fortigate-test-ap-southeast-2:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      BalanceWebTrafficOverPort: 443
      CustomIdentifier: fgtASG
      ExpireLifecycleEntry: '300'
      FortiGateAdminCidr: 10.0.0.0/16
      FortiGateAdminPort: '8443'
      FortiGateAsgCooldown: '300'
      FortiGateAsgDesiredCapacity: '2'
      FortiGateAsgHealthCheckGracePeriod: '300'
      FortiGateAsgMaxSize: '4'
      FortiGateAsgMinSize: '2'
      FortiGateAsgScaleInThreshold: '25'
      FortiGateAsgScaleOutThreshold: '80'
      FortiGateElbTgHealthyThreshold: '3'
      FortiGateInstanceType: t2.small
      FortiGatePskSecret: $[taskcat_genpass_8]
      InternalLoadBalancerDnsName: fgtqsg-asg
      InternalLoadBalancingOptions: add a new internal load balancer
      KeyPairName: taskcat
      PrivateSubnet1CIDR: 10.0.1.0/24
      PrivateSubnet2CIDR: 10.0.3.0/24
      PublicSubnet1CIDR: 10.0.0.0/24
      PublicSubnet2CIDR: 10.0.2.0/24
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-fortinet-fortigate/
      VPCCIDR: 10.0.0.0/16
    regions:
    - ap-southeast-2
    s3_bucket: ''
    template: templates/workload-master.template

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (ex: [2018.817.210357])

 Note: Python Version (python3 required)

To find versions:
*Via taskcat*: `taskcat -V`
*Via pip3*: `pip3 show taskcat`

Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by andrew-glenn** [comment]
I worked with Troy out of band. This was an environment-based issue. Closing.
