### ISSUE TITLE
Sample CloudFormation templates for Direct Connect Services

### ISSUE THREAD

**Issue by Kishorep81** [aws-quickstart/taskcat#490]
Hello Team,

I would like to raise a feature request issue with the AWS QuickStart team to have sample CloudFormation templates for Direct Connect Services. I work for Reed Exhibitions UK and we have a requirement to create a hosted virtual interface. I understand that there are no templates for the Direct Connect service. 

Thanks
Kishore

**Comment by avattathil** [comment]
Hello @Kishorep81 lets move this discussion to email please contact me at tonynv@amazon.com so I can get more info on your use case! 

Thanks
—Tony
