### ISSUE TITLE
docker-installer.sh should generate docker commands to run as the current user

### ISSUE THREAD

**Issue by nokesc** [aws-quickstart/taskcat#497]
When running **taskcat test run**, the docker container runs as root .  This causes the generated report folder and files to be owned by root, and user must sudo to delete those files.  Also, it is a best practice to not run as root.

Recommendation:  Capture the current user uid and launch using that.  You will then need to map the .aws directory to the root folder in the container because that user does not have a home directory in the container (unless the caller is root, so maybe conditional logic is needed):

docker run -it --rm **--user $(id -u):$(id -g)** -v ${HOME}/.aws:**/.aws** -v $(pwd):/mnt ${DOCKER_IMAGE} taskcat $@

**Comment by andrew-glenn** [comment]
@nokesc thanks for the feedback. This is a great first contribution opportunity. Are you able to make a PR with the same?

**Comment by tonynv** [comment]
Archiving.. This is not in scope for v0.9 (Closing)
