### ISSUE TITLE
Lambda::Function create failed because package lambda is in us-east-1

### ISSUE THREAD

**Issue by villasv** [aws-quickstart/taskcat#508]
I have a test that runs on `us-east-1` and `us-east-2`. TaskCat will create its bucket on `us-east-1` by default, but when the deployment at `us-east-2` tries to use a packaged lambda, it tries to get it from `us-east-1` and errors.

```
2020-03-04 00:35:51.877000+00:00
CREATE_FAILED
AWS::Lambda::Function
CloudWatchMetricLambda
Error occurred while GetObject. S3 Error Code: PermanentRedirect.
S3 Error Message: The bucket is in this region: us-east-1.
Please use this region to retry the request (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 7390dfe9-edf1-45f4-a7ca-c3303ffeb4f5)
```

**To Reproduce**
`make test` on https://github.com/villasv/aws-airflow-stack

**Expected behavior**
Tests on `us-east-2` should pass.

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version: b1011e8

**Comment by andrew-glenn** [comment]
@villasv 

We recently added opt-in support for regional S3 buckets (#504). This should solve the issue you're seeing. FYI - it'll create a longer-term bucket in the format `tcat-<ACCOUNT HASH>-<REGION>`. We currently _do not_ delete the objects to avoid concurrency problems. (Although may change this in the future). 

Give that a go, let me know if things are still broken.

**Comment by villasv** [comment]
Worked like a charm, sorry for missing that config option :-)
