### ISSUE TITLE
Support xml-Style output

### ISSUE THREAD

**Issue by serverhorror** [aws-quickstart/taskcat#509]
**Describe the bug**
Taskcat only produces text output. That makes integration with "unit" test hard.

**To Reproduce**
1. run any project in AWS CodeBuild via `taskcat test run`
2. try to integrate `taskcat_outputs/` with CodeBuild reports

**Expected behavior**
I would like to see an option to output that is compatible with [Working with Test Reporting in CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/test-reporting.html)

It would be perfect if the was exposed in a nice way so that this could be included in "larger" test runs where I am able to:

* deploy the taskcat stack
* run tests against the stack
* do a cleanup

**Version (Please make sure you are running the latest version of taskcat)
 - taskcat-0.9.13
- Python version 3.8

**Additional context**

**Comment by andrew-glenn** [comment]
Awesome feature idea. The _only_ concern that comes to my mind is the preview nature of CodeBuild reports currently. However I can see this being included with an `—experimental` flag, to cover that.

Ex:

`taskcat test run —experemental —codebuild-reports `

**Comment by serverhorror** [comment]
If it’s just some version of „—output xunit“ that would be extremely
helpful.

To get off the ground with a way lower entry barrier that would be enough
-- 
Martin Marcher
*Immersive Consultant*
http://martinmarcher.com
Mobile/Cell: +43 / 660 / 62 45 103 <+436606245103>
UID: ATU68801424
GISA: 27227527
GLN: 9110020666184

**Comment by bryanburke** [comment]
I second this. Being able to ingest the test results for display in a tool like Jenkins would be very useful, especially for review by non-developer cloud architects. Ant's JUnit XML schema is here for reference: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

**Comment by andrew-glenn** [comment]
_(cross-post)_ OK. I think it's time to abstract out the output stuff so it's easy to extend. Similar to how we abstract the CLI modules. TAPOutput, JUnit output, etc.

**Comment by andrew-glenn** [comment]
Output modularization is being tracked via https://github.com/aws-quickstart/taskcat/issues/549

**Comment by tonynv** [comment]
Archiving.. This is not in scope for v0.9 (Closing)
