### ISSUE TITLE
How to create a fixed name CloudFormation stack

### ISSUE THREAD

**Issue by rajalokan** [aws-quickstart/taskcat#520]
**Describe the bug**
Not a bug. Rather how can I create a stack with fixed name? My usecase need a fixed named stack to be created as part of CI/CD. I was hoping if I can use taskcat for this?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (9.15)

**Additional context**
N/A

**Comment by rajalokan** [comment]
More Context : I would like to use hash of my commit instead of UUID as unique suffix. That way I can evaluate stack_name in my CI/CD and add logic to not re-create ( or create first time).

**Comment by andrew-glenn** [comment]
Sure. it's pretty straight forward to add this. Just want to clarify: The UUID is used in both the stack *and* the tags assigned to a stack. I presume that won't be an issue, but changing it in one will change it in both.

**Comment by andrew-glenn** [comment]
Cross-post: see #562
