### ISSUE TITLE
[Request] TAP-compliant output

### ISSUE THREAD

**Issue by bryanburke** [aws-quickstart/taskcat#527]
[Test Anything Protocol](http://testanything.org/), TAP for short, is a simple plain text protocol for communication of test results between tools in a language-agnostic way. TAP-formatted results are parseable by a variety of libraries and tools, and several tools exist to convert between TAP and other common formats such as JUnit XML. Support for TAP-compliant output would be useful in automated CI workflows, where a variety of testing and static analysis tools often come together to produce a more complete picture of code quality.

**Comment by andrew-glenn** [comment]
OK. I think it's time to abstract out the output stuff so it's easy to extend. Similar to how we abstract the CLI modules. TAPOutput, JUnit output, etc.

**Comment by andrew-glenn** [comment]
Output modularization is being tracked via https://github.com/aws-quickstart/taskcat/issues/549. TAP-specific output is a dependency

**Comment by tonynv** [comment]
Archiving.. This is not in scope for v0.9 (Closing)
