### ISSUE TITLE
Runtime valid value didn't include nodejs12.x

### ISSUE THREAD

**Issue by cc4i** [aws-quickstart/taskcat#529]
**Describe the bug**
Runtime valid value didn't include nodejs12.x and cause validation errorr.

[ERROR  ] :     line 170 [3030] [Check if properties have a valid value] You must specify a valid value for Runtime (nodejs12.x). Valid
                                                               values are ['dotnetcore1.0', 'dotnetcore2.0', 'dotnetcore2.1',
                                                               'go1.x', 'java8', 'nodejs', 'nodejs4.3-edge', 'nodejs4.3',
                                                               'nodejs6.10', 'nodejs8.10', 'nodejs10.x', 'provided', 'python2.7',
                                                               'python3.6', 'python3.7', 'ruby2.5']

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*?
*Custom template*

2. Attach or link a copy of the template if possible (**remove any sensitive info**)
  LambdaESCognito:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: Centralized Logging - Lambda solution helper functions
      Environment:
        Variables:
          LOG_LEVEL: 'INFO' #change to WARN, ERROR or DEBUG as needed
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 300
      Role: !GetAtt LambdaESCognitoRole.Arn
      Code:
        S3Bucket: !Join ["-", [!FindInMap ["SourceCode", "General", "S3Bucket"], Ref: "AWS::Region"]]
        S3Key: !Join ["/", [!FindInMap ["SourceCode", "General", "KeyPrefix"],  "clog-auth.zip"]]

3. Provide the parameters that you passed. (**remove any sensitive info**)
4. How did you install taskcat? (docker or pip3)
pip3

5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat?
6. Is your AWS environment configured via `aws configure`?

**Expected behavior**

**Screenshots**

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (ex: [2018.817.210357])
0.9.17

 Note: Python Version (python3 required)
v3.7.4:e09359112e

To find versions:
*Via taskcat*: `taskcat -V`
*Via pip3*: `pip3 show taskcat`

Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by andrew-glenn** [comment]
@cc4i - We leverage `cfn-lint` under the hood for linting purposes. I've spot-checked the last several releases of `cfn-lint` and I'm seeing specfile support for `nodejs12.x`. Can you confirm you have the latest `cfn-lint` installed (0.29.1 as of this writing)?

Ultimately, this is more of a cfn-lint issue, and less of a taskcat issue. I'm happy to help debug though.

**Comment by cc4i** [comment]
Thanks for quick reply. I've updated cfn-lint to latest 0.29.1 and fixed issue. Previous version was 0.23.
