### ISSUE TITLE
Add CLI command to upload to S3

### ISSUE THREAD

**Issue by clayvan** [aws-quickstart/taskcat#547]
**Describe the bug**
Definitely not a bug, but rather a feature request. Taskcat is awesome, and provides subcommands for linting so that you don't need to run a full `taskcat test run`. I'd also like a subcommand for uploading the CF templates to S3 so I don't have to do a full test run to do so.

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version 0.9.17

I could potentially copy what taskcat is doing under the hood. ex: `aws s3 sync ...` but then the lambda functions don't get zipped up.

**Comment by andrew-glenn** [comment]
It’s funny. We had this in v 0.8.x and wa us intentionally left out with the refactor for 0.9. We’ve been bit by this being missing lately as well.

It’s very much on our radar.

**Comment by andrew-glenn** [comment]
The underlying structure is there. We just need a CLI entrypoint

**Comment by clayvan** [comment]
Sweet, great to hear. The lack of it is only a minor annoyance, so not the worst thing in the world in the meantime.

Thanks for the awesome tool!
