### ISSUE TITLE
Missing Capabilities [CAPABILITY_NAMED_IAM] option

### ISSUE THREAD

**Issue by jorgebonilla** [aws-quickstart/taskcat#56]
I was unable to test an IAM roles/Policy CFT due to missing option to add CAPABILITY_NAMED_IAM

Error:
An error occurred (InsufficientCapabilitiesException) when calling the CreateStack operation: Requires capabilities : [CAPABILITY_NAMED_IAM]

**Line 919 of taskcat/stacker.py:**
self.set_capabilities('CAPABILITY_IAM')
**should probably be:**
self.set_capabilities('CAPABILITY_NAMED_IAM')

**Comment by santiagocardenas** [comment]
We are evaluating the pros and cons of making that change.

I'm fairly certain that if we changed that line, your test run would still fail across regions because of resource name collisions on global services like IAM or S3, for example.

Are you only testing in a single region?

**Comment by jorgebonilla** [comment]
If there were a way to run one test at the time, or even one region at the time then it wouldn't fail. Perhaps an option to "sequential test" instead of  current "parallel" behavior if you will.

To answer the initial question, yes, we will be indeed testing in many regions.

**Comment by jorgebonilla** [comment]
Agreed, and understood. However, this issue can also be solved by having an install phase before the testing phase, where we could install the IAM roles required AND other CFT that are not being tested, before we run the actual templates that we want to test.
And the IAM role CFT could be previously tested separately in a single region.
Just a thought.

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/taskcat/pull/50/commits/d7805f97f9a0b2d27e5cd6d50fb89b68f8da6aa5
