### ISSUE TITLE
How to use taskcat deploy which is an alpha feature? There is no manual on how to use the other commands. What are the sub commands?

### ISSUE THREAD

**Issue by yrathams1990** [aws-quickstart/taskcat#560]
I replaced “test” command with “deploy” and I got the below warnings and error. 

version 0.9.17
00:18:11  [0;30;43m[WARN   ][0m : deploy is in alpha feature, use with caution
00:18:11  [0;30;43m[WARN   ][0m : Region not set in credential chain, defaulting to us-east-1
00:18:11  [0;30;47m[INFO   ][0m : fetching git repo https://github.com/aws-quickstart/quickstart-run.git
00:18:11  [0;30;41m[ERROR  ][0m : GitProtocolError unexpected http resp 401 for https://github.com/aws-quickstart/quickstart-run.git/info/refs?service=git-upload-pack
[Pipeline] }

I am running the below command from the Jenkins Pipeline and got the above error. 
taskcat deploy run -p ./RDS/ci

**Comment by andrew-glenn** [comment]
_This was addressed out of band. Closing._
