### ISSUE TITLE
Supporting custom stack name - prefix, suffix, fixed

### ISSUE THREAD

**Issue by sshvans** [aws-quickstart/taskcat#562]
**Feature request**

Ability to customize the stack name for stacks created by taskcat test run.
It will especially be useful when user is using an external system to generate a name which they want to use to associate with the stack, such as Jenkins job id or CodeBuild run id.

Proposal:
Add following 3 flags:
- *--custom-stackname-prefix* 'stackprefix'
- *--custom-stackname-suffix* 'stacksuffix'
- *--custom-stackname* 'hardcoded-name'

**Comment by sshvans** [comment]
I feel that instead of creating additional flags, it will be a better fit for taskcat config file. 
User can provide following 3 attribute values either at the project level or at per test level. 
Only 1 of the following attributes are allowed.

- stackname
- stackname-suffix
- stackname-prefix

Example:
-------------------
project:
    stackname: "mystack"

project:
    stackname-prefix: "myprefix"

project:
    stackname-suffix: "suffix"

OR

tests:
    test1:
        stackname: "my-test1-stackname"
    
    test2:
        stackname-prefix: "my-test2-prefix"
    
    test3:
        stackname-suffix: "my-test3-suffix"

**Comment by sshvans** [comment]
@jaymccon @andrew-glenn what do you guys think?

**Comment by andrew-glenn** [comment]
Pull requests are welcome.

**Comment by jaymccon** [comment]
seeing as this is niche, I'd vote for it being config only, and users wanting to can set with env vars at runtime similar to:

```
TASKCAT_PROJECT_STACKNAME_SUFFIX=${JOB_ID} taskcat test run
```
