### ISSUE TITLE
Add Ruby function support for packaging

### ISSUE THREAD

**Issue by clayvan** [aws-quickstart/taskcat#563]
**Describe the bug**
Not a but, but a feature request. I'd like the packaging library to support Ruby Gemfiles.

**Expected behavior**
I would expect some behavior similar to the bundler vendoring outlined here: https://docs.aws.amazon.com/lambda/latest/dg/ruby-package.html

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version 0.9.17

**Comment by jaymccon** [comment]
this can be done using docker packaging. Basically, just pop a Dockerfile into the root of your source folder build/cmd should output a zip to `/output/` in the container. Taskcat will do a docker build and run and then place the contents of the `/output/` folder into `packages/<FUNC_NAME>/`. https://github.com/aws-quickstart/taskcat/blob/master/tests/data/lambda_build_with_submodules/submodules/SomeSub/lambda_functions/source/TestFunc/Dockerfile

**Comment by clayvan** [comment]
Ah that makes sense! Any particular reason python packaging has its own logic instead of relying on docker packaging too?

**Comment by andrew-glenn** [comment]
Docker images and "packaging" lambdas came more recently. Taskcat has been on pypi from very early on.

Closing this as there are no outstanding issues.
