### ISSUE TITLE
AMIUpdater - "No query parameters were found for: AMZNEKS115."

### ISSUE THREAD

**Issue by schottsfired** [aws-quickstart/taskcat#569]
**Describe the bug**
The `update-ami` command fails with the following:

```
Message: 'No query parameters were found for: AMZNEKS115.'
Arguments: ('(Results for this codename are not possible.',)
```

https://github.com/aws-quickstart/taskcat/blob/master/taskcat/_amiupdater.py#L208-L211

**To Reproduce**
1. Check out https://github.com/aws-quickstart/quickstart-cloudbees-core/tree/develop.
2. Run `taskcat update-ami` in the project directory.

**Expected behavior**
All AMI IDs in the `/templates/` folder are updated to the latest version, if available.

**Version**
 - Taskcat Version 0.9.17

**Comment by andrew-glenn** [comment]
I’ll have a fix for this later today.

**Comment by schottsfired** [comment]
Hi @andrew-glenn, apologies, this was an error on our side in the Spot node template. Fixed by https://github.com/cloudbees/quickstart-cloudbees-core/commit/dcfda0cf96dcf68609710660fb6bde404a9228e6.

Love that we can `update-ami` at any time now!

Thanks

**Comment by andrew-glenn** [comment]
No worries! I’d much prefer to chase down a couple of false alarms than not have a line of communication to our users.

When you get a moment - I’d love to pick your brain about a few things. Would you mind sending me an email? andglenn@ amazon dot com.

Thanks
