### ISSUE TITLE
Need a way to override upstream CI parameters without git conflicts

### ISSUE THREAD

**Issue by agamzn** [aws-quickstart/taskcat#57]
Need a way for local parameter overrides. 

Edit: see #58 , 

To use: 
- define your parameter overrides by adding them to ci/override.json. 
- If keys exist in both the original parameter file, and override.json, the values in override.json will win. 
- Additional keys present in the override file, but *not* the original parameters will be added to the parameter list.

**Comment by agamzn** [comment]
PR Merged; Closing.

**Comment by agamzn** [comment]
Edge case found when using the global ovverride (~/.taskcat_global_override.json) with a docker container install. Currently working through remediation.

**Comment by avattathil** [comment]
@agamzn suggestion move the  `~/.taskcat_global_override.json` the docker mountpoint

**Comment by agamzn** [comment]
See #63 for docker-container adjustments.

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/taskcat/commit/4966cc2ae32700730054dcba7c5b12692a03f80e https://github.com/aws-quickstart/taskcat/commit/ac1fa50d89748f41755b72972753603badc3e020
