### ISSUE TITLE
"taskcat test list" and "taskcat test clean ALL" does not support ap-northeast-3, af-south-1 and eu-south-1 regions

### ISSUE THREAD

**Issue by muktadadariya** [aws-quickstart/taskcat#582]
**Describe the bug**
I want to list and delete the stacks created by taskcat in all the regions. When I run these command "taskcat test list" and "taskcat test clean ALL", it lists and deletes the stack from all the regions except ap-northeast-3, af-south-1 and eu-south-1

**To Reproduce**
1. Deploy stack in us-east-1, ap-northeast-3, af-south-1 and eu-south-1 regions
2. Wait for it to complete
3. Run this "taskcat test list" and "taskcat test clean ALL"

**Expected behavior**
it should list and delete all the stacks

**Actual behavior**
it only list and delete stack from us-east-1. 

**Screenshots**
![Screen Shot 2020-07-20 at 3 36 38 PM](https://user-images.githubusercontent.com/26233332/87978725-e858d200-ca9e-11ea-8719-118d1a02811b.png)

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (0.9.18)

 Note: Python Version (python3 required)

To find versions:
*Via taskcat*: `taskcat -V`
*Via pip3*: `pip3 show taskcat`

Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by jaymccon** [comment]
looks like this is fixed by updating botocore, so that `get_available_regions` returns new regions. The exception there is `ap-northeast-3` which is not listed as supported, but is. For those wanting to use `taskcat test clean` in that region you can specify the region to clean with `--region`
