### ISSUE TITLE
Created a GitHub Action to run taskcat - OK to publish to the GitHub Marketplace?

### ISSUE THREAD

**Issue by ShahradR** [aws-quickstart/taskcat#586]
Hello!

I've been working on a GitHub Action to run taskcat on my GitHub-hosted CI/CD pipelines, and I was thinking of publishing it on the GitHub Marketplace. I just wanted to make sure it was OK with the taskcat team before going forward, and if so, make sure there weren't any changes you'd like to see before I published it.

I worked off the [taskcat/taskcat](https://hub.docker.com/r/taskcat/taskcat) Docker container, and leveraged the [`configure-aws-credentials`](https://github.com/aws-actions/configure-aws-credentials) action to handle credentials + mask the account ID in the logs. Logs generated in the `taskcat_outputs` directory won't have masks though, so there is a risk of exposing the AWS account ID if the resource names reference it. I'm hoping to handle this in a future release, but [I documented it in the README in the meantime](https://github.com/ShahradR/action-taskcat#managing-credentials).

You can find [the action's source here](https://github.com/ShahradR/action-taskcat), and you can [see sample output in GitHub workflow here!](https://github.com/ShahradR/action-taskcat/runs/900979764?check_suite_focus=true#step:5:68)

Let me know what you think!

**Comment by andrew-glenn** [comment]
No objections!

The only concern I have is that you may end up fielding issues that are taskcat related versus specific to your action. However, a clearly defined README should address that, and I don't anticipate that to be a major burden.

The only other thing.. if/when we decide to vendor our an official action, we may build on your work. It's not a roadmap item right now but there may be an opportunity for your contributions to become "official" versus community driven. It doesn't affect our position on your action either way, but more curious if that's something you would be open to?

**Comment by ShahradR** [comment]
Awesome, thank you very much! [I just published it now.](https://github.com/marketplace/actions/run-taskcat-tests)

For the actions vs. taskcat issues, that's a good idea—I'll update the README and point people to this repo for taskcat-specific issues. Worst-case scenario, it'll just be a bit of triage on the issues. Shouldn't be a big deal!

As for having this work used as the basis for an official AWS action, no issues from me—that'd be kinda neat, actually!

And thank you for the heads up re: the Docker container issue, I'll keep an eye on it!
