### ISSUE TITLE
Taskcat variable for the current bucket name 

### ISSUE THREAD

**Issue by tjtaill** [aws-quickstart/taskcat#603]
Hi

Is there a taskcat variable that will give the current bucket name that taskcat is using regardles if generated or specified?

For example $[taskcat_getval_s3_bucket] will that work or is there something else I can use
to inject the current taskcat bucket name into my cf template params ?

**Comment by andrew-glenn** [comment]
`$[taskcat_autobucket]` behaves exactly how you'd expect. The naming is a little counter-intuitive, as the original behavior was different. I'm happy to add a`$[taskcat_s3_bucket]` as an alias with the same net effect.

**Comment by tjtaill** [comment]
My understanding $[taskcat_autobucket] generates a new random bucket name not the one that taskcat is creating to upload your templates to and run the tests from it is that bucket name I need to get programmatically and pass to my template arguments this is very useful when testing nested stacks

**Comment by andrew-glenn** [comment]
Not quite. `$[taskcat_autobucket]` is the bucket that assets are uploaded to prior to stack creation.

If you find this is not true then I need to investigate.

**Comment by tjtaill** [comment]
Actually you are correct I mis understood what it does based on this article https://aws.amazon.com/blogs/infrastructure-and-automation/a-deep-dive-into-testing-with-taskcat/ which says this "taskcat_autobucket – Generates a valid Amazon Simple Storage Service (Amazon S3) bucket name. For example, taskcat-tag-sample-taskcat-project-5fba6597." Thanks it is perfect closing this
