### ISSUE TITLE
Holisitic support for Windows paths.

### ISSUE THREAD

**Issue by techcto** [aws-quickstart/taskcat#611]
Why was functions > packages removed?

In the Quickstart guide, having the zips is still a requirement.  Is there another way to generate the zips now?

Currently CopyZips: in the function template still requires these and is failing for me.

**Comment by jaymccon** [comment]
moved this issue, as the path handling on windows needs to be addressed in taskcat, not eks Quick Start.

**Comment by tonynv** [comment]
Archiving.. This is not in scope for v0.9 (Closing)
