### ISSUE TITLE
[Feature Request] Zipfile behavior - add comment to archive containing hash of source

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/taskcat#619]
In `taskcat package`, a zip archive is created for use as a Lambda function. This archive contains source, and libraries. Each time this package is built, it's very likely the hash will be different due to upstream libraries (etc).

In turn, this means that even though the _source_ of the function hasn't changed, the archive is uploaded to S3, due to a different hash on the file itself. It's desirable to cut down on needless S3 uploads, especially in low-bandwith or long-distance data transfers.

Talking this over with @troy-ameigh, we came up with this approach.

### In packaging: 

- Look for a hashfile within `<sourcedir>`. This file is a list of hashes for the source. It's up to the author of the lambda (currently) to maintain this list. 
- Hash this file, add it as a comment to the zip after packaging. This can be done with the built-in `zipfile` library.

_Setting the comment_
```
>>> import zipfile
>>> with zipfile.ZipFile('lambda.zip', 'a') as zip:
...     zip.comment = b'sha:abcdef12345'
...
...
>>>
```
_Demonstrating it's there_
```
❯ unzip -z lambda.zip
Archive:  lambda.zip
sha:abcdef12345
```

### In S3 uploads:
- Inspect the zipfile for a comment following this regex (regex pattern tbd). If found, this hash is used for comparison, instead of a hash of the entire archive.
- If that's changed (comparing with S3 ETag (current behavior)) - upload. Otherwise, don't. 

## Net change to S3 upload behavior: 
- Simply provides a mechanism for an alternate hash for object comparisons. The existing logic around uploading if the object doesn't exist, deletes, etc, still apply.

**Comment by andrew-glenn** [comment]
It may be desirable to have this behavior be opt-in. An `upload` section of the config is on the radar. `custom_zipfile_hash: True` could be set under `upload`.

**Comment by jaymccon** [comment]
I think more discussion and some experiments should be done before putting pen to paper. In my opinion a much simpler implementation would be to try and ensure that a zip file with the same contents has the same hash, that way no change is needed to the upload behavior.

I have attempted to solve determinism for zip files with some success by doing all zip builds, even if there are no build steps by doing the build in docker and doing the following:

* setting all timestamps to a specific date. As file properties like timestamps are stored in metadata, differing timestamps result in differing hashes
* removing metadata from pip install packages. Metadata often includes non-deterministic data, resulting in the same pip install having a different hash

**Comment by jaymccon** [comment]
I guess I feel that getting the same zip contents to have the same hash is a hard problem, that this feature as proposed will not address.
