### ISSUE TITLE
Add GP3 As a Valid Volume Type

### ISSUE THREAD

**Issue by girvenj** [aws-quickstart/taskcat#625]
**Describe the bug**
The Linter does not recognize GP3 as a valid volume type.  "You must specify a valid value for VolumeType (gp3). Valid values are ["gp2", "io1", "io2", "sc1", "st1", "standard"]"

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*? I am running a template with GP3 configured through taskcat 
2. Attach or link a copy of the template if possible (**remove any sensitive info**)  You can use any template just change the volume type to GP3.  
3. Provide the parameters that you passed. (**remove any sensitive info**) gp3 instead of gp2

4. How did you install taskcat? (docker or pip3) Taskcat is not the issue.  The linter needs gp3 added.  

5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat?  N/A

6. Is your AWS environment configured via `aws configure`? Yes

**Expected behavior**
It should accept GP3 as a valid volume type.

**Screenshots**
Sample Error:
[ERROR  ] : Linting detected issues in: /home/girvenj/quickstart-microsoft-activedirectory/templates/ad-2.template
[ERROR  ] :     line 336 [3030] [Check if properties have a valid value] You must specify a valid value for VolumeType (gp3). Valid values

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (ex: [2018.817.210357])

 Note: Python Version (python3 required)

To find versions:
*Via taskcat*: `taskcat -V`
version 0.9.20

*Via pip3*: `pip3 show taskcat`

Name: taskcat
Version: 0.9.20
Summary: An OpenSource Cloudformation Deployment Framework
Home-page: https://aws-quickstart.github.io/taskcat/
Author: Tony Vattathil, Jay McConnell, Andrew Glenn, Santiago Cardenas, Shivansh Singh
Author-email: tonynv@amazon.com, jmmccon@amazon.com, andglenn@amazon.com, sshvans@amazon.com
License: Apache License 2.0
Location: /home/girvenj/.local/lib/python3.8/site-packages
Requires: docker, PyYAML, jsonschema, botocore, cfn-lint, pip, reprint, mock, yattag, requests, boto3, dulwich, dataclasses-jsonschema, setuptools, tabulate, jinja2
Required-by:

Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by andrew-glenn** [comment]
We inherit the linting behavior from `cfn-lint`. I suspect that the underlying CloudFormation specfiles haven't been updated to reflect `gp3` volume types. 

As a courtesy, I've copied this over to https://github.com/aws-cloudformation/cfn-python-lint/issues/1829 for tracking

**Comment by PatMyron** [comment]
released in [`cfn-lint 0.43.0`](https://github.com/aws-cloudformation/cfn-python-lint/releases/tag/v0.43.0):
[`pip3 install cfn-lint --upgrade`](https://github.com/aws-cloudformation/cfn-python-lint/pull/1804)
