### ISSUE TITLE
Fails after lint with DockerException

### ISSUE THREAD

**Issue by iainelder** [aws-quickstart/taskcat#636]
**Describe the bug**

I'm trying taskcat for the first time today and I ran into a confusing error.

On any template I've tried so far, the linter passes and then Taskcat fails with a DockerException.

Here's the exact output:

```text
$ taskcat test run
 _            _             _   
| |_ __ _ ___| | _____ __ _| |_ 
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_ 
 \__\__,_|___/_|\_\___\__,_|\__|
                                


version 0.9.21
[INFO   ] : Linting passed for file: /home/isme/Repos/build38-notes/rds-via-session-manager/minimal.yml
[ERROR  ] : DockerException Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**To Reproduce**
1. I'm using a custom template.
2. I've pasted a copy of the template below.
3. No parameters are required
4. I installed taskcat using pipx 0.15.6.0 which was installed using Python 3.8.5.
5. I'm using a profile to run taskcat.
6. My AWS environment is configured with `aws configure`.

**Expected behavior**

As it's my first time using the program, I'm not really sure, but I was expecting to maybe see some output about creating a CloudFormation template, and nothing to do with Docker.

**Version**

Taskcat version is 0.9.21.

Python version is 3.8.5.

**Custom Template**

minimal.yml:

```yml
AWSTemplateFormatVersion: 2010-09-09
Description: Minimal Template

Resources:
  Dummy:
    Type: AWS::CloudFormation::WaitConditionHandle
```

.taskcat.yml:

```yml
project:
  name: minimal-test
  regions:
    - eu-west-1
tests:
  default:
    template: minimal.yml
```

**Additional context**

I don't have Docker installed. According to README it's not required for my example.

> Note: docker is only required if building lambda functions using a Dockerfile

I see a similar issue reported in #602 where the discussion dives into Docker images. So is Docker actually required or not? I'm fine with installing Docker to make this work, but I'd like it to be clear in the instructions if that's the case.

**Comment by iainelder** [comment]
My example works with version Taskcat version 0.9.1. See the full output below.

It's the earliest version of 0.9.x I could find that this example works for. (I ran into #355 when using the initial release.)

```text
$ taskcat test run
 _            _             _   
| |_ __ _ ___| | _____ __ _| |_ 
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_ 
 \__\__,_|___/_|\_\___\__,_|\__|
                                


version 0.9.1

[WARN   ] : A newer version of taskcat is available (0.9.21)
[INFO   ] : To upgrade pip version    [ pip install --upgrade taskcat]
[INFO   ] : To upgrade docker version [ docker pull taskcat/taskcat ]

[INFO   ] : Lint passed for test default on template /home/isme/Repos/build38-notes/rds-via-session-manager/minimal.yml
[WARN   ] : Region not set in credential chain, defaulting to us-east-1
[S3: -> ] s3://tcat-minimal-test-fcd7u0se/minimal-test/stack.yaml
[S3: -> ] s3://tcat-minimal-test-fcd7u0se/minimal-test/minimal.yml
[INFO   ] : ┏ stack Ⓜ tCaT-minimal-test-default-73c2e403349c44eca93bb31c199b0ad0                     [INFO   ] : ┣ region: eu-west-1                                                                      [INFO   ] : ┗ status: CREATE_COMPLETE                                                                
[INFO   ] : Collecting CloudFormation Logs
[INFO   ] : Collecting logs for tCaT-minimal-test-default-73c2e403349c44eca93bb31c199b0ad0
[INFO   ] : 	 |StackName: tCaT-minimal-test-default-73c2e403349c44eca93bb31c199b0ad0
[INFO   ] : 	 |Region: eu-west-1
[INFO   ] : 	 |Logging to: /home/isme/Repos/build38-notes/rds-via-session-manager/taskcat_outputs/tCaT-minimal-test-default-73c2e403349c44eca93bb31c199b0ad0-eu-west-1-cfnlogs.txt
[INFO   ] : 	 |Tested on: Wednesday, 06. January 2021 02:40PM
[INFO   ] : ------------------------------------------------------------------------------------------
[INFO   ] : ResourceStatusReason: 
[INFO   ] : Stack launch was successful
[INFO   ] : ==========================================================================================
[INFO   ] : Reporting on arn:aws:cloudformation:eu-west-1:584690922383:stack/tCaT-minimal-test-default-73c2e403349c44eca93bb31c199b0ad0/a79c3890-5024-11eb-9741-06ad0b2a6f83
[INFO   ] : Deleting stack: arn:aws:cloudformation:eu-west-1:584690922383:stack/tCaT-minimal-test-default-73c2e403349c44eca93bb31c199b0ad0/a79c3890-5024-11eb-9741-06ad0b2a6f83
[INFO   ] : ┏ stack Ⓜ tCaT-minimal-test-default-73c2e403349c44eca93bb31c199b0ad0                     [INFO   ] : ┣ region: eu-west-1                                                                      [INFO   ] : ┗ status: DELETE_COMPLETE

**Comment by iainelder** [comment]
The earliest version that gives me the DockerException is 0.9.14.

The latest version that does the right thing is 0.9.13.

I'll continue to use 0.9.13 in my own environment while I await guidance for how to resolve the Docker issue.

Just installing Docker didn't fix it for me (I used `apt install docker.io`).

**Comment by AndySchuetz** [comment]
I had the same error with taskcat version 0.9.23 on Mac.  After launching docker desktop, taskcat runs without error.

**Comment by sboardwell** [comment]
@iainelder / @AndySchuetz: there is a workaround if you don't need to package Lambda functions.

See: https://github.com/aws-quickstart/taskcat/issues/602#issuecomment-689808244

**Comment by iainelder** [comment]
@sboardwell thanks for sharing! I had no idea that packaging Lambda functions was the reason for the Docker requirement.

Are you saying that if I use `package_lambda: false` I can avoid this issue?

**Comment by sboardwell** [comment]
Correct. I have added:
```yaml
project:
  name: myproject
  # For package_lambda: false, see: https://github.com/aws-quickstart/taskcat/issues/602#issuecomment-689808244
  package_lambda: false
  regions:
    - us-west-1
...
```
