### ISSUE TITLE
Add a verbose flag

### ISSUE THREAD

**Issue by chmreid** [aws-quickstart/taskcat#653]
**Describe the bug**

When I run `taskcat lint`, the program starts to perform actions, but it does not provide any indication to the user of what it's doing or what files it is checking. If I don't specify any input files, I expect the program to print help, or if it starts to do things, I expect it to tell me what it is doing (what actions is it performing, on what files,  etc).

Further confusing me is the fact that taskcat help suggests there is an `-i` flag to specify input files. So if I am not specifying an input file via `-i`, what input files is it using??

<s>The program does not print any information about what files it is checking or what it is doing.</s> (**EDIT:** taskcat does print what files it checked during the lint process, but _only if the lint checks succeed_. If there are any errors, the line number is reported, but no file name is reported.) There is also no --verbose flag or anything similar available to force the program to print out what it's doing or what files it's checking. The documentation and Readmes do not mention the lint action.

On an unrelated note - while looking for information in the readme, one  of the links to your documentation in the readme is broken (https://aws-quickstart.github.io/taskcat/apidocs/taskcat/testing/index.html).

This is a confusing and frustrating first exposure to taskcat.

**Comment by tonynv** [comment]
Use --debug
