### ISSUE TITLE
Architecture Diagram Visualization

### ISSUE THREAD

**Issue by afonsoppedro** [aws-quickstart/taskcat#659]
Hi @andrew-glenn 

I’m Afonso and I came across your repo and I took the liberty to scan it with the tool that I am currently developing. If I caught your attention, feel free to take a look at the [following diagram](https://dashboard.codeshield.io/public/result/38f15df7-49ab-41d9-973b-569bdbd26e2d?utm_source=github.com&utm_medium=share-graphs&utm_campaign=teamb) and let me know your thoughts on this. I am really interested to get your feedback and understand if the diagram we presented matches the architecture you have in mind.

**Comment by andrew-glenn** [comment]
This tool looks useful in general, but the output doesn't really apply to this project.

**Comment by afonsoppedro** [comment]
Thanks for letting me know @andrew-glenn , do you want to elaborate on the use case you have in mind? Can you provide me with links to projects that'd be worth further investigating?
