### ISSUE TITLE
how-to-fix-clienterror-an-error-occurred-accessdenied-when-calling-the-createBucket operation

### ISSUE THREAD

**Issue by anishdevps1** [aws-quickstart/taskcat#672]
**Describe the bug**

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*?
2. Attach or link a copy of the template if possible (**remove any sensitive info**)
3. Provide the parameters that you passed. (**remove any sensitive info**)
4. How did you install taskcat? (docker or pip3)
5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat?
6. Is your AWS environment configured via `aws configure`?

**Expected behavior**

**Screenshots**

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (ex: [2018.817.210357])

 Note: Python Version (python3 required)

To find versions:
*Via taskcat*: `taskcat -V`
*Via pip3*: `pip3 show taskcat`

Note: both version should match

To update taskcat run:
 *for docker* : `docker pull taskcat/taskcat`
 *for pip3*: `pip3 install --upgrade taskcat`

**Additional context**

**Comment by andrew-glenn** [comment]
Check the permissions on the credentials you're using when you invoke taskcat. You'll need permissions to create an S3 bucket. Alternately, provide an S3 bucket that's been created and use the `s3bucket` config option.

https://aws-quickstart.github.io/taskcat/docs/schema/taskcat_schema.html#project_s3_bucket
