### ISSUE TITLE
spaces() - necessary?

### ISSUE THREAD

**Issue by ilyash-b** [aws-quickstart/taskcat#674]
https://github.com/aws-quickstart/taskcat/blob/a82a9292762dd62b8867674f99169026abd8988d/taskcat/_cli_modules/list.py#L73-L77

Why not `' ' * number`?

**Comment by andrew-glenn** [comment]
No preference either way. In the interests of transparency, the CLI modules were created under a pretty tight deadline so you're likely to find little things like this. 

PRs are welcome if you're so inclined.
