### ISSUE TITLE
Track Cloudformation Stack Changes by Taskcat

### ISSUE THREAD

**Issue by WahidSyed** [aws-quickstart/taskcat#676]
Hi,

We have introduced Taskcat as our Automated Testing Tool for our existing Cloudformation Templates. The testing works fine, but we also have a requirement for Taskcat to identify the Changed state of the Stack and perform the testing based on the same. But we are unable to achieve this using Taskcat. 

Kindly suggest.

**Comment by WahidSyed** [comment]
Hi @andrew-glenn,

Kindly help understand how to read the stack that is already deployed and test based on that read. Like my case is - I've a stack 'A' which is deployed and there are 'X' resources that got created. Out of those 'X' resources that were created, I would like to test stack 'A' by Deleting or Modifying the resources so that the existing infra state shall not break. 

Kindly help 

Thank You!
Syed.

**Comment by andrew-glenn** [comment]
Stack updates and tests based on state changes are not supported by taskcat.
