### ISSUE TITLE
Continuously fails with Python exception

### ISSUE THREAD

**Issue by MacInnis** [aws-quickstart/taskcat#82]
It blows up with a Python exception, although AFAIK, i've configured everything correctly.  Here's the stack trace:

Traceback (most recent call last):
  File "/home/macinna/.local/bin/taskcat", line 58, in <module>
    main()
  File "/home/macinna/.local/bin/taskcat", line 46, in main
    tcat_instance.validate_template(taskcat_cfg, test_list)
  File "/home/macinna/.local/lib/python3.5/site-packages/taskcat/stacker.py", line 717, in validate_template
    self.define_tests(taskcat_cfg, test)
  File "/home/macinna/.local/lib/python3.5/site-packages/taskcat/stacker.py", line 1522, in define_tests
    if self.check_json(cfntemplate, quite=True, strict=False):
  File "/home/macinna/.local/lib/python3.5/site-packages/taskcat/stacker.py", line 1569, in check_json
    parms = json.loads(jsonin)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

I noticed that the template file's content-type in S3 is set to binary/octet-stream.  So I suspect (although I've not tested it) that this is causing it to get read back by boto as an array of bytes rather than a string.

**Comment by agamzn** [comment]
Tagging this with 'bug' category. @MacInnis and I will sync-up in person this week to hash this out.

**Comment by avattathil** [comment]
If the parms file has integer values try converting them two strings
1 to "1"

**Comment by avattathil** [comment]
@MacInnis can you confirm that you have the latest version. This line https://github.com/aws-quickstart/taskcat/blob/master/taskcat/stacker.py#L929 should address this condition

**Comment by bczoma** [comment]
It seems I'm having the same issue:
```
[taskcat] :Validate Template in test[2az-europe]
[INFO   ] :No cleanup value set
[INFO   ] : - (Defaulting to cleanup)
Traceback (most recent call last):
  File "/usr/local/bin/taskcat", line 58, in <module>
    main()
  File "/usr/local/bin/taskcat", line 46, in main
    tcat_instance.validate_template(taskcat_cfg, test_list)
  File "/usr/local/lib/python3.5/dist-packages/taskcat/stacker.py", line 717, in validate_template
    self.define_tests(taskcat_cfg, test)
  File "/usr/local/lib/python3.5/dist-packages/taskcat/stacker.py", line 1526, in define_tests
    if self.check_json(cfntemplate, quite=True, strict=False):
  File "/usr/local/lib/python3.5/dist-packages/taskcat/stacker.py", line 1573, in check_json
    parms = json.loads(jsonin)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

I have upgraded taskcat to the latest:

````
pip show taskcat
Name: taskcat
Version: 2018.531.110151
Summary: An OpenSource Cloudformation Deployment Framework
Home-page: https://aws-quickstart.github.io/taskcat/
Author: Tony Vattathil, Santiago Cardenas, Shivansh Singh, Jay McConnell, Andrew Glenn
Author-email: tonynv@amazon.com, sancard@amazon.com, sshvans@amazon.com, jmmccon@amazon.com, andglenn@amazon.com
License: Apache License 2.0
Location: /usr/local/lib/python3.5/dist-packages
Requires: boto3, pyfiglet, pyyaml, tabulate, yattag
Required-by:
```

Params file has no integer values.

**Comment by avattathil** [comment]
Please provide steps to reproduce

**Comment by bczoma** [comment]
I have tried to re-run the tests for an existing quickstart, which worked in the past.

Here are the steps for a new created Ubuntu EC2:

```
# prep env, install tools - some steps may not be required
sudo apt update
sudo apt upgrade
sudo ln -s /usr/bin/python3 /usr/bin/python
sudo apt install python3-pip
sudo pip3 install taskcat
sudo apt install awscli
aws configure   # provide your config
# clone my project with workaround to recurse submodules 
git clone https://github.com/aws-quickstart/quickstart-solace-vmr.git
cd quickstart-solace-vmr/
sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules; cat .gitmodules
git submodule sync
git submodule init
git submodule update
cd ..
# try to run taskcat
taskcat -c quickstart-solace-vmr/ci/config.yml
```

**Comment by avattathil** [comment]
This issue was handled in https://github.com/aws-quickstart/taskcat/issues/66. 
Please update to the latest version of taskcat. (2018.718.145150).

` pip3 install --upgrade taskcat`
