### ISSUE TITLE
Serverless code testing 

### ISSUE THREAD

**Issue by ritwik-singh-yash** [aws-quickstart/taskcat#85]
Is it possible to use taskcat for testing cloudformation templates that contain serverless code or the transform tag?
My organisation has an application that is launched by nested cloudformation templates that contain serverless code. When I try to test the templates through taskcat it gives me the following error:-
[ERROR  ] :An error occurred (ValidationError) when calling the CreateStack operation: CreateStack cannot be used with templates containing Transforms.

If it is possible to test cloudformation templates containing transform tag, how can we achieve it?

**Comment by avattathil** [comment]
@ritwik-singh-yash taskcat does a strick syntax check to validate json and yaml templates. The purpose behind this is to ensure that we can load the object as base json or yaml for linting purposes. For example, in json if there is a trailing comma validation will fail (cfn validation does not take trailing commas into consideration). 
Is it possible for you to provide a sample or copy of your template so I can reproduce the error and work on a fix?

**Comment by ankur-jain-yash** [comment]
@avattathil you can access it at below location...
https://github.com/aws-quickstart/quickstart-datalake-yash/pull/1

**Comment by vsnyc** [comment]
@ankur-jain-yash I have made pull request https://github.com/aws-quickstart/taskcat/pull/89 for this. While that is being reviewed, please use this [fork](https://github.com/vsnyc/taskcat) as a workaround. To test with the forked version of taskcat, you can do the following:
1. Checkout taskcat fork and quickstart-datalake-yash in the same parent directory e.g.
```
projects
|
+-- taskcat
|
+-- quickstart-datalake-yash
```
2. From the root directory (i.e. `projects` in the example above) execute:
` python3 taskcat/taskcat.py -c quickstart-datalake-yash/ci/config.yml -n`

**Comment by avattathil** [comment]
The solution is being worked in https://github.com/aws-quickstart/taskcat/pull/89 by @vsnyc

**Comment by avattathil** [comment]
@vsnyc any further update needed here?

**Comment by vsnyc** [comment]
Verified that the latest taskcat works with Serverless transforms. Closing.
