### ISSUE TITLE
Auto Input Generation

### ISSUE THREAD

**Issue by tonynv** [aws-quickstart/taskcat#86]
Scan CFN Parameters and build a scaffold for taskcat inputs
Tag Parameters without Defaults value as NEED_VALUES

**Comment by avattathil** [comment]
@virtlima do you want to take a stab at this.  I will provide some code that handles json template?

**Comment by andrew-glenn** [comment]
Tagging for v0.9 feature request.

**Comment by andrew-glenn** [comment]
tag: WONTFIX
