### ISSUE TITLE
Piping curl output to sudo is dangerous

### ISSUE THREAD

**Issue by codevbus** [aws-quickstart/taskcat#88]
The deployment/install instructions currently state:

`curl -s https://raw.githubusercontent.com/aws-quickstart/taskcat/master/installer/docker-install-master| sudo python -E`

Piping curl output to `sudo $command` is a pretty dangerous anti-pattern to ask users to engage in. Any chance we could get an updated set of instructions?

**Comment by avattathil** [comment]
The installer script basically does docker pull and add a wrapper then move it into you default path
`echo "docker run -it --rm -v ${HOME}/.aws:/root/.aws -v \$(pwd):/mnt taskcat/taskcat taskcat \$@" >>taskcat`

You dont have to use sudo
https://github.com/aws-quickstart/taskcat/blob/master/installer/docker-install-master#L47-L60

If you have suggestions. Happy to consider them

**Comment by avattathil** [comment]
Since `sudo` is not required I am closing this issue. Feel free to reopen if you need.

**Comment by codevbus** [comment]
I think my point was less about whether or not it's actually required vs. it being explicitly declared as an installation instruction in the documentation.

**Comment by avattathil** [comment]
I agree, I will update the documentation to make non root option default. 

Reopening..

**Comment by avattathil** [comment]
Add pip3 install instruction that do not require sudo 
https://aws-quickstart.github.io/taskcat/#installing-via-pip3-for-those-who-do-not-want-to-use-the-docker-installer

Fixed in https://github.com/aws-quickstart/taskcat/commit/a3c87b89cd659b9c9d97df00d55cdb7bd5dd3189
