### ISSUE TITLE
issue with multiple python versions

### ISSUE THREAD

**Issue by garvitsingh-aws** [aws-quickstart/taskcat#9]
Hi,

I was having issue due to multiple python versions installed. Since taskcat works only with python 2.7 and under my installation pip was installing using python 3. This was breaking the installation.

quick fix:
python3 -m pip install -U --force-reinstall pip
python -m pip install -U --force-reinstall pip

this will ensure your pip uses correct python version for taskcat installation

**Comment by avattathil** [comment]
Thanks for the tip. I will add it to the documentation
