### ISSUE TITLE
Using same auto-generated value for multiple parameters

### ISSUE THREAD

**Issue by sshvans** [aws-quickstart/taskcat#94]

**Comment by agamzn** [comment]
Use case?

**Comment by vsnyc** [comment]
Say you have two parameter inputs: `Password` and `ConfirmPassword`. If you generate a random value for `Password`, then the `ConfirmPassword` field must be passed the same randomly generated value.

**Comment by avattathil** [comment]
We can use these getter/setter 
https://github.com/aws-quickstart/taskcat/blob/master/taskcat/stacker.py#L349-L353
to store the generated password. I suggest adding a new runtime injection parameter maybe `$[taskcat_confirm-genpass]` which simply returns the last password that was generated. Easy enough to do if you @sshvans @agamzn @vsnyc concur. I can add it.

**Comment by vsnyc** [comment]
Will this work when there are two password (e.g. admin, user) and two confirm password fields? Reference to a generated value will be a more futureproof solution. i.e.

Key: MyPassword
Value: taskcat-genpass

Key: ConfirmPassword
Value: taskcat-getval-$MyPassword.

Where, the MyPassword itself is an evaluated token which must match a defined key in the input file.

**Comment by avattathil** [comment]
Yep  agree change _password to a dict and store the generated referencing the current parameter that is being processed. 

Then add the get value method as @vsync suggested.

**Comment by agamzn** [comment]
Agreed. Make it happen, captain!

Sent from my iPhone

On Jul 3, 2018, at 15:56, Tony Vattathil <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep agree change _password to a dict and store the generated referencing the current parameter that is being processed.

Then add the get value method as @vsync<https://github.com/vsync> suggested.

**Comment by avattathil** [comment]
@sshvans https://github.com/aws-quickstart/taskcat/commit/a1a542d1a71daf1ba98c84a90dcdc4966b2fabcf  should resolve this issue. When you get the chance can you pull the latest and give it a spin?

**Comment by sshvans** [comment]
Works!
