### ISSUE TITLE
NoSuchKey doesn't have a 'msg' attribute

### ISSUE THREAD

**Issue by agamzn** [aws-quickstart/taskcat#95]
[This commit](https://github.com/aws-quickstart/taskcat/commit/f295fadd4e00bbc2a29add980aa71f824fca76f0) introduced a race condition when raised exceptions do not contain a 'msg' attribute within the object. 

[Fix is in this commit](https://github.com/aws-quickstart/taskcat/commit/121b129fa9a0b15c7b9704d7c016e2222ec25f72). Needs validation.

**Comment by avattathil** [comment]
Look like you passed the wong conif file

**Comment by virtlima** [comment]
I am going to isolate in a clean docker container, and run through this --> https://github.com/avattathil/quckstart_lab again

**Comment by virtlima** [comment]
Everything works, it was a environment issue with my laptop.
