### ISSUE TITLE
Add flag to save console output of instance if stack fails. 

### ISSUE THREAD

**Issue by agamzn** [aws-quickstart/taskcat#96]
Sometimes userdata fails and outputs to console. Need option to grab console before terminating.

**Comment by jaymccon** [comment]
might want to have a look at [linux-utils cwl integration](https://github.com/aws-quickstart/quickstart-linux-utilities/blob/master/quickstart-cfn-tools.source#L159-L183), this way you can view logs in cwl after stack deletes.

**Comment by agamzn** [comment]
After review, there are too many variables here to make this practical. Closing.
